/**
 * Enterprise benchmark source configurations.
 *
 * These sources map SJTU discipline directions to official enterprise case,
 * solution, product, technology, project, or newsroom pages with reusable
 * science/engineering visuals. Commercial translation pages are preferred over
 * generic news because the enterprise group is a benchmark for how research and
 * engineering outcomes become market-facing value.
 */
import { prisma } from '../prisma.js';

export interface EnterpriseSourceConfig {
  discipline: string;
  name: string;
  url: string;
  sourceType: string;
  category: string;
  crawlTier: string;
  crawlStatus: string;
  adapterType: string;
  visualValue: string;
  strategyHint?: string;
  notes: string;
  commercialIntent?: string;
  commercialPriority?: 'primary' | 'secondary' | 'fallback';
}

export const ENTERPRISE_SOURCES: EnterpriseSourceConfig[] = [
  {
    discipline: '船舶海洋与建筑工程学院',
    name: 'Kongsberg Maritime',
    url: 'https://www.kongsbergmaritime.com/products/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '船舶海洋装备、自动化船桥、声呐、海洋工程系统和海试场景图',
    strategyHint: '优先抓 products 入口；已验证可静态发现 bridge systems、propulsion、simulation 等产品页并入库',
    notes: 'discipline=船舶海洋与建筑工程学院；挪威海事技术头部企业；2026-06-03 产品页真实入库 11 条',
  },
  {
    discipline: '船舶海洋与建筑工程学院',
    name: 'Arup Projects',
    url: 'https://www.arup.com/projects/all-projects/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '建筑工程、基础设施、桥梁、城市韧性和工程项目案例图',
    strategyHint: '静态 fetch 返回 500；使用 enterprise:browser-batch 渲染 projects 列表可入库项目图',
    notes: 'discipline=船舶海洋与建筑工程学院；国际工程咨询与建筑工程设计标杆；2026-06-03 browser_render 入库 3 条',
  },
  {
    discipline: '船舶海洋与建筑工程学院',
    name: 'Autodesk Newsroom',
    url: 'https://adsknews.autodesk.com/en/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '建筑工程数字化、BIM、施工管理、产品设计与制造、数字孪生、AI/ML 工作流配图、客户项目案例图',
    strategyHint: 'WordPress 站点，支持静态发现；customer-stories 有 bot 防护改用 newsroom 入口',
    notes: 'discipline=船舶海洋与建筑工程学院；Autodesk 官方 newsroom；AEC/PD&M/创新/可持续发展/客户故事栏目；commercialIntent=customer_story；2026-06-03 因 customer-stories bot拦截改用 newsroom',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Siemens Energy',
    url: 'https://www.siemens-energy.com/global/en/home/press-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '燃机、氢能、储能、电网设备、能源系统工程图和工厂场景',
    strategyHint: '静态发现当前为 0 链接；需改 stories/solutions 入口或 browser_render',
    notes: 'discipline=机械与动力工程学院；能源动力系统头部企业',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Rolls-Royce',
    url: 'https://www.rolls-royce.com/media/press-releases.aspx',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '航空发动机、船舶动力、核动力、小型模块堆和工程制造场景图',
    strategyHint: '优先抓 press releases；创新和产品服务页面作为补充入口',
    notes: 'discipline=机械与动力工程学院；动力系统与航空发动机标杆',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Caterpillar News',
    url: 'https://www.cat.com/en_US/articles/customer-stories.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '工程机械、动力系统、矿山设备、施工装备和自动化作业场景图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或更稳定的 customer story 列表入口',
    notes: 'discipline=机械与动力工程学院；工程机械和动力装备商业化应用案例来源；commercialIntent=customer_story；2026-06-03 static fetch failed',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'Huawei News',
    url: 'https://www.huawei.com/en/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '通信设备、网络基础设施、终端产品、ICT 技术图和研发场景',
    strategyHint: 'news 列表静态抓取不足；可用人工提供的 consumer wearable / 产品营销页作为受控 URL 清单补充',
    notes: 'discipline=电子信息与电气工程学院；ICT 与通信设备头部企业；2026-06-03 用户提供 wearable 页面入库 5 条',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'Qualcomm OnQ',
    url: 'https://www.qualcomm.com/news/onq',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '移动通信、射频、芯片平台、AI 终端和无线技术解释图',
    strategyHint: 'OnQ 列表静态发现不足；可用 AI research / Snapdragon 产品详情页做受控 URL 清单入库',
    notes: 'discipline=电子信息与电气工程学院；无线通信与移动芯片标杆；2026-06-03 替代详情页入库 2 条',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Technical Blog',
    url: 'https://developer.nvidia.com/blog',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'GPU、AI 计算、通信加速、仿真、数据中心和技术架构图',
    strategyHint: '技术博客含有大量架构图和性能图；优先采含 figure/图表的博文详情',
    notes: 'discipline=电子信息与电气工程学院；AI 计算与电子信息技术解释来源；commercialIntent=technical_explanation',
    commercialIntent: 'technical_explanation',
    commercialPriority: 'secondary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Customer Stories',
    url: 'https://www.nvidia.com/en-us/case-studies/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'AI、GPU、仿真、数字孪生、机器人和行业解决方案的客户案例图、性能图和产品场景图',
    strategyHint: '优先抓 case studies；重点保留行业应用、性能提升、解决方案架构和产品落地场景',
    notes: 'discipline=电子信息与电气工程学院；AI 计算商业化落地案例来源；commercialIntent=case_study',
    commercialIntent: 'case_study',
    commercialPriority: 'primary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Data Center Solutions',
    url: 'https://www.nvidia.com/en-us/data-center/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '数据中心 GPU、AI 训练集群、推理平台、网络架构和机架系统图',
    strategyHint: '优先抓产品线和解决方案页面；保留架构图和硬件渲染图',
    notes: 'discipline=电子信息与电气工程学院；NVIDIA 数据中心产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Autonomous Machines',
    url: 'https://www.nvidia.com/en-us/autonomous-machines/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '自主机器、AI 边缘计算、Jetson 平台、机器人感知和自动驾驶平台图',
    strategyHint: '优先抓产品页和解决方案页；保留边缘计算架构图、机器人平台图',
    notes: 'discipline=电子信息与电气工程学院；NVIDIA 自主机器产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Healthcare Solutions',
    url: 'https://www.nvidia.com/en-us/industries/healthcare/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '医学影像 AI、数字病理、基因组分析、手术机器人和药物发现可视化',
    strategyHint: '优先抓行业解决方案页；保留医疗 AI 架构图和临床场景图',
    notes: 'discipline=电子信息与电气工程学院；NVIDIA 医疗行业方案补充；commercialIntent=case_study',
    commercialIntent: 'case_study',
    commercialPriority: 'primary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Robotics',
    url: 'https://www.nvidia.com/en-us/industries/robotics/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '机器人平台、Isaac 平台、自主导航、仿真平台和感知pipeline图',
    strategyHint: '优先抓行业页和解决方案页；保留机器人技术图和仿真截图',
    notes: 'discipline=电子信息与电气工程学院；NVIDIA 机器人行业方案补充；commercialIntent=case_study',
    commercialIntent: 'case_study',
    commercialPriority: 'primary',
  },
  {
    discipline: '电气工程学院',
    name: 'ABB News',
    url: 'https://new.abb.com/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '电气化、变频器、机器人、工业自动化、电网和工厂场景图',
    strategyHint: '优先抓 news；按 electrification / robotics 主题页细分二阶段优化',
    notes: 'discipline=电气工程学院；电气与自动化跨学科头部企业',
  },
  {
    discipline: '电气工程学院',
    name: 'Schneider Electric Newsroom',
    url: 'https://www.se.com/us/en/about-us/newsroom/news/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '配电、能效管理、楼宇电气、数据中心基础设施和工业能源图',
    strategyHint: '优先抓 newsroom press releases；已通过真实小批量采集，继续保留工程设备、电气基础设施和楼宇系统图',
    notes: 'discipline=电气工程学院；能源管理与电气自动化标杆',
  },
  {
    discipline: '电气工程学院',
    name: 'Eaton News Releases',
    url: 'https://www.eaton.com/us/en-us/company/news-insights/news-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '配电、储能、数据中心电气、工业电气设备和能源管理场景图',
    strategyHint: '优先抓 news releases；保留电气设备、能源基础设施和应用案例图',
    notes: 'discipline=电气工程学院；电气设备与能源管理标杆补充来源',
  },
  {
    discipline: '自动化与感知学院',
    name: 'Boston Dynamics Blog',
    url: 'https://bostondynamics.com/blog/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '机器人实物、移动感知、控制系统、产品演示和视频封面图',
    strategyHint: '优先抓 blog；视频页面仅取 poster/og:image，不抓视频本体',
    notes: 'discipline=自动化与感知学院；移动机器人和感知控制标杆',
  },
  {
    discipline: '自动化与感知学院',
    name: 'Boston Dynamics Spot',
    url: 'https://bostondynamics.com/products/spot',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'Spot 四足机器人、工业检测、遥控操作、自主导航和现场部署场景图',
    strategyHint: '产品页含大量产品渲染和实景图；browser_render 确保 JS 渲染的 hero 和 gallery 可捕获',
    notes: 'discipline=自动化与感知学院；Boston Dynamics Spot 四足机器人产品补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '自动化与感知学院',
    name: 'Boston Dynamics Stretch',
    url: 'https://bostondynamics.com/products/stretch',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'Stretch 仓储机器人、箱搬运、物流自动化、机械臂和仓库场景图',
    strategyHint: '产品页含实景和系统图；browser_render 捕获 JS 渲染的交互式展示图',
    notes: 'discipline=自动化与感知学院；Boston Dynamics Stretch 仓储机器人补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '自动化与感知学院',
    name: 'FANUC America News',
    url: 'https://www.fanucamerica.com/news-resources/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '工业机器人、自动化产线、机床控制、工厂应用案例图',
    strategyHint: '优先抓 news-resources/news；若列表分页动态化则标注 browser_render',
    notes: 'discipline=自动化与感知学院；工业机器人与数控自动化标杆',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Google Research Blog',
    url: 'https://research.google/blog/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'static_html',
    visualValue: 'AI 研究图、模型示意、数据可视化、交互系统和计算机视觉案例',
    strategyHint: '仅作为企业研究视觉补充；商业化参照优先抓 customer stories、product/solution pages 和行业应用页',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；企业研究视觉补充，不作为商业化优先入口；commercialIntent=research_supplement',
    commercialIntent: 'research_supplement',
    commercialPriority: 'fallback',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Microsoft AI Customer Stories',
    url: 'https://www.microsoft.com/ai/ai-customer-stories',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: 'AI 客户案例、行业应用、业务成效、产品能力和解决方案架构图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或替代公开 customer story 入口',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；AI 商业化客户案例来源；commercialIntent=customer_story',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Microsoft AI Co-Innovation Labs',
    url: 'https://aiotlabs.microsoft.com/en/case-studies',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: 'AI 原型、行业解决方案、技术组合、客户成果和实验室共创案例图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或替代公开 case studies 入口',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；AI 共创商业化案例来源；commercialIntent=case_study',
    commercialIntent: 'case_study',
    commercialPriority: 'primary',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Microsoft Azure Blog',
    url: 'https://azure.microsoft.com/en-us/blog/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'Azure 云架构、AI 服务、数据可视化、云原生技术和开发平台配图',
    strategyHint: 'Azure blog 是 WordPress 站；静态发现可靠，优先抓含架构图和技术插图的博文',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；Microsoft Azure 技术博客补充；commercialIntent=technical_explanation',
    commercialIntent: 'technical_explanation',
    commercialPriority: 'primary',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Microsoft Industry Stories',
    url: 'https://www.microsoft.com/en-us/industry',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'Microsoft 行业解决方案、数字转型、AI 应用案例和企业技术场景图',
    strategyHint: '行业页可静态抓取；保留行业应用案例和解决方案架构图',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；Microsoft 行业解决方案补充；commercialIntent=customer_story',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Microsoft Xbox News',
    url: 'https://news.xbox.com/en-us/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '游戏硬件、主机设计、游戏截图、UI 界面和娱乐场景图',
    strategyHint: 'Xbox news 是 WordPress；可静态抓取含产品图和游戏概念图的新闻',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；Microsoft 游戏与消费硬件补充；commercialIntent=customer_story',
    commercialIntent: 'customer_story',
    commercialPriority: 'fallback',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'ASML News',
    url: 'https://www.asml.com/en/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '光刻机、洁净室、半导体制造设备、技术解释图和工业摄影',
    strategyHint: '优先抓 news；technology 页面作为二阶段补充',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；半导体装备头部企业',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'ASML Technology Deep Dives',
    url: 'https://www.asml.com/en/technology',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'EUV 光刻技术、极紫外光源、光学投影系统、纳米级制程技术解释图',
    strategyHint: '技术页含丰富架构图和原理图；优先抓 lithography、EUV、numerical aperture 等技术详情页',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；ASML 技术深度内容补充；commercialIntent=technical_explanation',
    commercialIntent: 'technical_explanation',
    commercialPriority: 'primary',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'ASML Products EUV',
    url: 'https://www.asml.com/en/products/euv-lithography-systems',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'EUV 光刻机、Twinscan 系统、光刻模块、晶圆传输和洁净室场景图',
    strategyHint: '产品页含丰富渲染图和实景图；保留产品渲染、洁净室和系统工程图',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；ASML 产品系统补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'TSMC Newsroom',
    url: 'https://pr.tsmc.com/english/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'manual',
    visualValue: '晶圆厂、先进制程、封装、半导体制造和研发新闻图',
    strategyHint: '优先抓 PR newsroom；若静态列表不足，后续改 browser_render',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；晶圆制造头部企业',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'Arm Newsroom',
    url: 'https://www.arm.com/company/success-library/arm-designs/powercast',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '芯片 IP、AI 计算、边缘处理器、半导体生态、客户成功案例和应用场景图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或更稳定的 success library 列表入口',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；芯片架构与半导体 IP 商业化案例来源；commercialIntent=success_story；2026-06-03 static fetch failed',
    commercialIntent: 'success_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'ZEISS Semiconductor Manufacturing',
    url: 'https://www.zeiss.com/semiconductor-manufacturing-technology/home.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '光刻光学、半导体制造设备、EUV光源、晶圆检测和洁净室场景图',
    strategyHint: 'ZEISS 半导体技术页面，browser_render 渲染',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；ZEISS 半导体制造技术；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'ZEISS Microscopy Solutions',
    url: 'https://www.zeiss.com/microscopy/en/solutions.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '显微镜、光学系统、科研成像、生命科学和工业检测产品场景图',
    strategyHint: 'ZEISS 全站 Cloudflare 403 静态不可用；采用 browser_render 渲染产品页和解决方案列表',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；ZEISS 光学与显微成像产品线补充；需 browser_render',
  },
  {
    discipline: '生物医学工程学院',
    name: 'ZEISS Medical Technology',
    url: 'https://www.zeiss.com/medical-technology/en/products.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '医学影像设备、眼科设备、手术显微镜、数字病理和医院场景图',
    strategyHint: 'ZEISS 全站 Cloudflare 403；采用 browser_render 渲染医疗技术产品页',
    notes: 'discipline=生物医学工程学院；ZEISS 医疗技术产品线补充；需 browser_render；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '材料科学与工程学院',
    name: 'BASF News',
    url: 'https://www.basf.com/global/en/media/news-releases',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '化工材料、实验室、工厂、分子材料和应用产品图',
    strategyHint: '优先抓 news releases；research press 图文适合作为材料视觉案例',
    notes: 'discipline=材料科学与工程学院；化工材料头部企业',
  },
  {
    discipline: '材料科学与工程学院',
    name: 'Corning News',
    url: 'https://www.corning.com/worldwide/en/about-us/news-events/news-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '玻璃、陶瓷、光纤、先进材料、实验制造和产品微观结构图',
    strategyHint: '优先抓 news releases；innovation 页面作为二阶段补充',
    notes: 'discipline=材料科学与工程学院；先进玻璃陶瓷与光学材料标杆',
  },
  {
    discipline: '材料科学与工程学院',
    name: 'Dow Press Releases',
    url: 'https://corporate.dow.com/en-us/news/press-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'manual',
    visualValue: '材料科学、低碳材料、包装材料、热管理材料、实验室和应用场景图',
    strategyHint: '官网静态入口真实采集会落到 HTTP 403 或品牌页；不绕过，后续改用人工采集或替代材料企业入口',
    notes: 'discipline=材料科学与工程学院；材料科学与化工材料标杆补充来源',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Xylem Newsroom',
    url: 'https://www.xylem.com/en-us/about-xylem/newsroom/press-releases/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '水处理、水资源监测、泵站、传感器和环境工程案例图',
    strategyHint: '优先抓 applications / watermark 等可静态入库页面；press releases 作为二阶段入口继续调优',
    notes: 'discipline=环境科学与工程学院；水技术与环境工程头部企业；2026-06-03 真实小批量入库 10 条',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Xylem Solutions',
    url: 'https://www.xylem.com/en-us/markets/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '水处理解决方案、泵站系统、智能水务、管网管理和水基础设施场景图',
    strategyHint: 'Xylem solutions 重定向到 markets 页面；优先抓 markets 下的水处理、管网、监测子页面；含丰富系统架构图和场景图',
    notes: 'discipline=环境科学与工程学院；Xylem 解决方案/市场页面补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Xylem Applications',
    url: 'https://www.xylem.com/en-us/applications/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '市政供水、工业水处理、建筑排水、农业灌溉和水务数字化应用场景图',
    strategyHint: '优先抓 applications 下的行业应用页面；保留场景化工程图和基础设施图',
    notes: 'discipline=环境科学与工程学院；Xylem 行业应用页面补充；commercialIntent=case_study',
    commercialIntent: 'case_study',
    commercialPriority: 'primary',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Xylem Products Services',
    url: 'https://www.xylem.com/en-us/products--services/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '泵站设备、水处理系统、水质监测传感器、供水产品和工程场景图',
    strategyHint: 'browser_render 渲染产品页捕获 JS 懒加载图',
    notes: 'discipline=环境科学与工程学院；Xylem 产品页面补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Xylem Newsroom Overview',
    url: 'https://www.xylem.com/en-us/about-xylem/newsroom/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '水技术新闻、环境工程案例、水利基础设施和水务创新场景图',
    strategyHint: 'browser_render 渲染 newsroom 列表页，获取 JS 动态图',
    notes: 'discipline=环境科学与工程学院；Xylem newsroom 入口补充',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Veolia Newsroom',
    url: 'https://www.veolia.com/en/newsroom/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '水处理、废弃物资源化、环境服务、资源循环、低碳基础设施和工程案例图',
    strategyHint: '优先抓 newsroom news；保留 water、waste、energy、resource efficiency 和环境工程项目图',
    notes: 'discipline=环境科学与工程学院；环境服务与资源循环标杆补充来源',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Orsted News',
    url: 'https://orsted.com/en/media-centre/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'manual',
    visualValue: '海上风电、可再生能源、低碳基础设施和能源工程场景图',
    strategyHint: '优先抓 media-centre/news；注意筛掉投资者关系纯文本新闻',
    notes: 'discipline=环境科学与工程学院；可再生能源和海上风电标杆',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Siemens Healthineers',
    url: 'https://www.siemens-healthineers.com/medical-imaging',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '医学影像设备、诊断系统、医院场景、AI 医疗和设备渲染图',
    strategyHint: '优先抓 medical-imaging 入口；可静态发现 CT、MRI、超声和数字医疗产品页',
    notes: 'discipline=生物医学工程学院；医学影像与诊断设备头部企业；2026-06-03 产品页真实入库 8 条',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Siemens Healthineers MRI',
    url: 'https://www.siemens-healthineers.com/magnetic-resonance-imaging',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'MRI 设备渲染图、磁共振系统、扫描场景、临床应用和 1.5T/3T 系统图',
    strategyHint: '优先抓产品详情子页面；保留设备渲染、临床场景和技术参数可视化',
    notes: 'discipline=生物医学工程学院；Siemens Healthineers MRI 产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Siemens Healthineers CT',
    url: 'https://www.siemens-healthineers.com/computed-tomography',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'CT 设备渲染图、双源 CT、能谱成像、心脏 CT 和系统架构图',
    strategyHint: '优先抓 CT 产品详情；保留设备渲染图和临床应用场景图',
    notes: 'discipline=生物医学工程学院；Siemens Healthineers CT 产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Siemens Healthineers Ultrasound',
    url: 'https://www.siemens-healthineers.com/ultrasound',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '超声设备、探头设计、临床成像示例、妇幼健康和POC超声场景图',
    strategyHint: '优先抓超声产品详情；保留设备图和临床成像示例',
    notes: 'discipline=生物医学工程学院；Siemens Healthineers 超声产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Siemens Healthineers Stories',
    url: 'https://www.siemens-healthineers.com/press-room/press-releases',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '医学影像临床案例、患者故事、技术突破、AI 医疗应用和医院创新场景图',
    strategyHint: '优先抓 stories 列表下的临床案例和技术创新故事；含丰富实景和设备使用图',
    notes: 'discipline=生物医学工程学院；Siemens Healthineers 故事内容补充；commercialIntent=customer_story',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'GE HealthCare Press Releases',
    url: 'https://www.gehealthcare.com/en-us/about/newsroom/press-releases',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '医学影像设备、AI 医疗、核医学、MR/CT/超声系统、临床研究和医院场景图',
    strategyHint: 'dry-run 可提图，但 active-batch 静态发现不足；后续需改用 browser_render 或更细新闻 API',
    notes: 'discipline=生物医学工程学院；医学影像与医疗技术标杆补充来源，暂作调优候选',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Newsroom',
    url: 'https://news.bostonscientific.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '介入医疗器械、植入设备、临床应用、产品细节和医疗技术新闻图',
    strategyHint: '优先抓 newsroom releases；排除回购、投资、财报和栏目页，真实采集必须人工复核',
    notes: 'discipline=生物医学工程学院；介入医疗器械标杆补充来源',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Newsroom P2',
    url: 'https://news.bostonscientific.com/news-releases?page=2',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '介入医疗器械、植入设备、临床案例新闻配图和医疗技术展示',
    strategyHint: '静态可采集 news-releases 分页；优先取产品配图和临床场景图，排除回购/投资/财报新闻',
    notes: 'discipline=生物医学工程学院；Boston Scientific newsroom 第2页补充',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Newsroom P3',
    url: 'https://news.bostonscientific.com/news-releases?page=3',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '介入医疗器械、植入设备、临床案例新闻配图和医疗技术展示',
    strategyHint: '静态可采集 news-releases 分页；优先取产品配图和临床场景图',
    notes: 'discipline=生物医学工程学院；Boston Scientific newsroom 第3页补充',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Products',
    url: 'https://www.bostonscientific.com/en-US/products.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '心血管、电生理、内窥镜、神经调控等全线医疗设备产品图和临床场景',
    strategyHint: 'bostonscientific.com 主站 406 防静态采集；browser_render 可渲染产品列表和详情页 JS 图',
    notes: 'discipline=生物医学工程学院；Boston Scientific 全线产品补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Cardiology',
    url: 'https://www.bostonscientific.com/en-US/medical-specialties/cardiology.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '心脏支架、球囊导管、WATCHMAN左心耳封堵器、起搏器和心脏介入设备图',
    strategyHint: 'browser_render 渲染心脏病学产品专题页',
    notes: 'discipline=生物医学工程学院；Boston Scientific 心脏病学专题补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Newsroom P4',
    url: 'https://news.bostonscientific.com/news-releases?page=4',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '介入医疗器械、植入设备、临床案例新闻配图和医疗技术展示',
    strategyHint: '静态可采集 news-releases 分页；优先取产品配图和临床场景图',
    notes: 'discipline=生物医学工程学院；Boston Scientific newsroom 第4页补充',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Electrophysiology',
    url: 'https://www.bostonscientific.com/en-US/products/electrophysiology.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '电生理导管、心脏mapping 系统、介入器械产品图和临床应用场景',
    strategyHint: 'Boston Scientific 主站防静态采集；browser_render 渲染电生理产品线页面，保留设备图、导管图和心跳mapping图',
    notes: 'discipline=生物医学工程学院；Boston Scientific 心脏介入产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Interventional Cardiology',
    url: 'https://www.bostonscientific.com/en-US/cardiology.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '冠脉支架、球囊导管、影像导管、结构性心脏病修复设备图',
    strategyHint: '优先抓产品页下的子产品线详情；保留器械图和手术示意',
    notes: 'discipline=生物医学工程学院；Boston Scientific 介入心脏病学产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Endoscopy',
    url: 'https://www.bostonscientific.com/en-US/endoscopy.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '内窥镜、消化道支架、ERCP 器械、微创手术设备图',
    strategyHint: '优先抓产品页下的子产品线详情；保留内窥镜设备图和消化内镜临床图',
    notes: 'discipline=生物医学工程学院；Boston Scientific 内窥镜产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '航空航天学院',
    name: 'Airbus Newsroom',
    url: 'https://www.airbus.com/en/newsroom',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '飞机、直升机、卫星、航天系统、飞行测试和工业制造图',
    strategyHint: '优先抓 newsroom；innovation 页面作为二阶段补充',
    notes: 'discipline=航空航天学院；航空航天系统头部企业',
  },
  {
    discipline: '航空航天学院',
    name: 'Airbus Innovation',
    url: 'https://www.airbus.com/en/innovation',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '航空创新、ZEROe 零排放飞机、氢动力、城市空中交通和未来概念图',
    strategyHint: 'innovation 页面有丰富概念图和技术渲染图；保留 ZEROe、hydrogen、UAM 等创新子页面',
    notes: 'discipline=航空航天学院；Airbus 创新技术补充',
  },
  {
    discipline: '航空航天学院',
    name: 'Airbus Commercial Aircraft',
    url: 'https://www.airbus.com/en/aircraft',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '客机产品线、A320/A350/A380 渲染图、客舱设计、机翼工程和飞行场景图',
    strategyHint: '产品页可静态采；保留机型渲染图、客舱布局图和工程细节图',
    notes: 'discipline=航空航天学院；Airbus 商用飞机产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '航空航天学院',
    name: 'Airbus Helicopters',
    url: 'https://www.airbus.com/en/helicopters',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '直升机产品线、H160/H175 渲染图、旋翼工程、搜救场景和飞行场景图',
    strategyHint: '直升机产品页含丰富产品图和场景图；保留机型渲染和运营场景图',
    notes: 'discipline=航空航天学院；Airbus 直升机产品线补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '航空航天学院',
    name: 'Airbus Defence and Space',
    url: 'https://www.airbus.com/en/space',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '卫星、空间系统、地球观测、通信卫星和航天器工程图',
    strategyHint: '空间产品页含卫星渲染和轨道场景图；保留航天器技术和系统工程图',
    notes: 'discipline=航空航天学院；Airbus 防务与航天补充；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '航空航天学院',
    name: 'Boeing Newsroom',
    url: 'https://boeing.mediaroom.com/news-releases-statements',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '飞机、航天器、防务系统、制造装配、飞行测试和工程新闻图',
    strategyHint: '优先抓 mediaroom releases；产品图库和视频页不纳入第一轮',
    notes: 'discipline=航空航天学院；航空航天制造头部企业',
  },

  // ── SpaceX：航天器与火箭产品页 ──

  {
    discipline: '航空航天学院',
    name: 'SpaceX Falcon 9',
    url: 'https://www.spacex.com/vehicles/falcon-9/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '猎鹰9号、可回收火箭、梅林发动机、发射台、整流罩、一级着陆、太空任务',
    strategyHint: '产品页需 browser_render；优先取火箭结构图、发动机特写、回收着陆序列、发射场景',
    notes: 'discipline=航空航天学院；可回收火箭工程标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '航空航天学院',
    name: 'SpaceX Falcon Heavy',
    url: 'https://www.spacex.com/vehicles/falcon-heavy/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '重型猎鹰、三芯并联、双助推器回收、深空发射、重型运载火箭工程',
    strategyHint: '产品页需 browser_render；优先取三芯并联结构图、双助推同步着陆场景、整流罩细节',
    notes: 'discipline=航空航天学院；重型运载火箭标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '航空航天学院',
    name: 'SpaceX Starship',
    url: 'https://www.spacex.com/vehicles/starship/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '星舰、超重型助推器、不锈钢箭体、热防护瓦、猛禽发动机、火星殖民概念、轨道加注',
    strategyHint: '产品页需 browser_render；优先取舰体结构渲染、发动机集群、热防护系统、火星场景概念图',
    notes: 'discipline=航空航天学院；下一代超重型航天器标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '航空航天学院',
    name: 'SpaceX Dragon',
    url: 'https://www.spacex.com/vehicles/dragon/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '载人龙飞船、货舱龙、对接国际空间站、发射逃逸系统、舱内布局、航天员界面',
    strategyHint: '产品页需 browser_render；优先取飞船结构剖面、对接场景渲染、舱内设备布局、人员操作场景',
    notes: 'discipline=航空航天学院；载人航天器产品标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'SpaceX Raptor Engine',
    url: 'https://www.spacex.com/vehicles/starship/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '猛禽全流量分级燃烧发动机、涡轮泵、燃烧室、3D打印部件、试车台',
    strategyHint: 'Starship 页内含 Raptor 发动机段落；需 browser_render 截取发动机特写、结构剖面、试车火焰序列',
    notes: 'discipline=机械与动力工程学院；全流量分级燃烧发动机工程标杆；与 Starship 同 URL 但按动力工程学科入库',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'SpaceX Starlink',
    url: 'https://www.starlink.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '星链卫星星座、相控阵天线、用户终端、卫星堆叠发射、地面网关、全球覆盖图',
    strategyHint: '产品页需 browser_render；优先取卫星堆叠结构图、相控阵天线特写、星座渲染、覆盖热力图',
    notes: 'discipline=电子信息与电气工程学院；低轨卫星通信系统产品标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },

  // ── 产品视觉参照：用户点名优先企业 ──

  {
    discipline: '产品视觉参照',
    name: 'Tesla Model Y',
    url: 'https://www.tesla.com/modely',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '电动车、极简产品叙事、交互 UI、场景化生活图、空气动力学设计渲染',
    strategyHint: '产品页，需 browser_render；优先取 hero 图、360 度车图、场景 lifestyle 图、UI 交互帧',
    notes: '产品视觉参照；电动车标杆；极简官网设计语言；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Tesla Cybertruck',
    url: 'https://www.tesla.com/cybertruck',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '赛博皮卡、未来感设计、材料质感、极端场景测试、工程能力可视化',
    notes: '产品视觉参照；极端工程美学和未来感设计标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Tesla Optimus',
    url: 'https://www.tesla.com/optimus',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '人形机器人、具身智能、工程细节摄影、制造场景、技术参数可视化',
    notes: '产品视觉参照；人形机器人产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Tesla Energy',
    url: 'https://www.tesla.com/energy',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'Megapack 储能系统、Powerwall 家用电池、太阳能面板、能源管理 UI、电网级储能场站',
    strategyHint: '产品聚合页需 browser_render；优先取储能产品结构图、场站实拍、能源管理界面',
    notes: 'discipline=机械与动力工程学院；大规模储能系统工程标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Tesla Megapack',
    url: 'https://www.tesla.com/megapack',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'Megapack 电网级储能、模块化电池柜、热管理系统、场站布局、安装部署实拍',
    strategyHint: '产品页需 browser_render；优先取储能柜结构剖面、场站规划图、安装序列',
    notes: 'discipline=机械与动力工程学院；电网级储能产品标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Tesla Solar',
    url: 'https://www.tesla.com/solarpanels',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '太阳能面板、Solar Roof 屋顶瓦片、户用光储系统、能效监控界面、安装场景',
    strategyHint: '产品页需 browser_render；优先取产品安装效果图、系统架构示意、能效数据面板',
    notes: 'discipline=环境科学与工程学院；户用清洁能源系统产品标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '计算机学院',
    name: 'Tesla AI & Autopilot',
    url: 'https://www.tesla.com/AI',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'FSD 自动驾驶、神经网络可视化、Occupancy Network、Dojo 超算、训练数据呈现',
    strategyHint: '产品页需 browser_render；优先取神经网络架构图、感知可视化、Dojo 超算硬件图',
    notes: 'discipline=计算机学院；自动驾驶AI系统可视化标杆；commercialIntent=technical_explanation',
    commercialIntent: 'technical_explanation',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Apple iPhone',
    url: 'https://www.apple.com/iphone/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '消费电子、材质特写、交互演示、色彩策略、产品 lifestyle 摄影',
    notes: '产品视觉参照；消费电子产品呈现全球标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Apple Vision Pro',
    url: 'https://www.apple.com/apple-vision-pro/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '空间计算、透明材质渲染、交互手势可视化、3D 产品分解图、沉浸体验场景',
    notes: '产品视觉参照；空间计算和沉浸感产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Apple Watch',
    url: 'https://www.apple.com/apple-watch/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '可穿戴设备、健康数据可视化、材质与配色展示、运动 lifestyle、表带设计',
    notes: '产品视觉参照；可穿戴设备 lifestyle 营销标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Unitree',
    url: 'https://www.unitree.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '四足与人形机器人、具身智能、运动控制、工程细节、产品矩阵展示',
    notes: '产品视觉参照；中国机器人企业产品呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Unitree G1',
    url: 'https://www.unitree.com/g1/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '人形机器人产品页、关节机构特写、动作序列、灵巧手演示',
    notes: '产品视觉参照；人形机器人单产品页面标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Unitree Go2',
    url: 'https://www.unitree.com/go2/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '四足机器人产品页、运动能力演示、户外场景、跟随交互、技术规格',
    notes: '产品视觉参照；四足机器人消费级产品页面标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Google Pixel 9',
    url: 'https://store.google.com/product/pixel_9',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'AI 手机、Gemini 整合、影像功能、材质与色彩、生活场景',
    notes: '产品视觉参照；AI 功能驱动的手机产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Google Phones',
    url: 'https://store.google.com/category/phones',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '手机全家桶、产品生态、功能对比、AI 卖点可视化',
    notes: '产品视觉参照；Google 设备生态产品对比页；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Google Watches',
    url: 'https://store.google.com/category/watches',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '智能手表、健康 tracking、生活方式、运动场景',
    notes: '产品视觉参照；可穿戴设备 lifestyle 展示页；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Xiaomi Global',
    url: 'https://www.mi.com/global/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '手机、IoT 生态、智能汽车、影像系统、小米生态链产品矩阵',
    notes: '产品视觉参照；中国消费电子和智能生态标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Xiaomi 15 Ultra',
    url: 'https://www.mi.com/global/product/xiaomi-15-ultra/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '影像旗舰手机、徕卡合作、镜头特写、摄影样张、材质细节',
    notes: '产品视觉参照；手机影像系统产品页标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Xiaomi Phone List',
    url: 'https://www.mi.com/global/product-list/phone/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '手机全家桶、产品线对比、色彩策略、系列化设计语言',
    notes: '产品视觉参照；消费者产品线和系列化呈现参考；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Dreame Tech',
    url: 'https://www.dreametech.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '清洁机器人、智能家居、机械结构展示、家居 lifestyle、产品系列',
    notes: '产品视觉参照；中国智能清洁机器人产品呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Dreame Robot Vacuums',
    url: 'https://www.dreametech.com/collections/robot-vacuums',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '扫地机器人产品线、激光导航、自动集尘、清洁能力可视化',
    notes: '产品视觉参照；清洁机器人品类产品矩阵展示页；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },

  // ── 产品视觉参照：补充头部企业 ──

  {
    discipline: '产品视觉参照',
    name: 'DJI',
    url: 'https://www.dji.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '无人机、航拍影像、手持云台、运动相机、空中视角、产品细节',
    notes: '产品视觉参照；全球无人机和影像设备产品呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Dyson',
    url: 'https://www.dyson.com/en',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '高端家电、空气动力学、透明结构展示、CMF 设计、工程美学 lifestyle',
    notes: '产品视觉参照；工程驱动产品美学全球标杆；改用 /en 路径绕过 Cloudflare；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Samsung Mobile',
    url: 'https://www.samsung.com/us/smartphones/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '折叠屏、AI 手机、Galaxy 生态、显示技术、生活方式摄影',
    notes: '产品视觉参照；全球手机出货量第一企业的产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Sony Electronics',
    url: 'https://electronics.sony.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'browser_render',
    visualValue: '影像、音频、娱乐硬件、传感器、产品 CMF、技术参数可视化',
    notes: '产品视觉参照；消费电子和影像传感器产品设计标杆；2026-06-03 electronics.sony.com 及 sony.com/en 均 Access Denied；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
    strategyHint: 'sony.com/en 集团门户和 electronics.sony.com 均返回 Access Denied；需真实浏览器带 header 或 CAPTCHA 方案',
  },
  {
    discipline: '产品视觉参照',
    name: 'Meta Quest',
    url: 'https://www.meta.com/quest/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'VR/MR 头显、空间交互、手柄设计、沉浸场景、混合现实体验',
    notes: '产品视觉参照；VR/MR 产品叙事和空间计算标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Meta Ray-Ban',
    url: 'https://www.meta.com/smart-glasses/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'AI 可穿戴、智能眼镜、生活方式融合、第一人称视角、时尚+科技',
    notes: '产品视觉参照；AI 可穿戴设备时尚化呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },

  // ── 产品视觉参照：汽车与机器人扩展 ──

  {
    discipline: '产品视觉参照',
    name: 'BYD Global',
    url: 'https://www.byd.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '新能源汽车、刀片电池、智能座舱、车规芯片、全球化品牌',
    notes: '产品视觉参照；中国新能源汽车全球销量第一的企业产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'NIO',
    url: 'https://www.nio.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '高端电动车、换电技术、NIO House lifestyle、自动驾驶可视化、设计语言',
    notes: '产品视觉参照；中国高端电动车 lifestyle 营销标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'XPeng',
    url: 'https://www.xpeng.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '智能驾驶、飞行汽车、机器人、智能座舱、OTA 技术可视化',
    notes: '产品视觉参照；智能驾驶和飞行汽车技术产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Rivian',
    url: 'https://rivian.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '户外电动车、冒险 lifestyle、露营场景、环保材料、制造工程图',
    notes: '产品视觉参照；户外冒险生活方式驱动的电动车品牌标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Figure AI',
    url: 'https://www.figure.ai/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '人形机器人、具身智能、灵巧手、工业应用、技术愿景叙事',
    notes: '产品视觉参照；人形机器人创业公司产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Agility Robotics',
    url: 'https://agilityrobotics.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '工业人形机器人、物流应用、仓库场景、Digital Twin、安全设计',
    notes: '产品视觉参照；工业人形机器人商用化产品标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },

  // ── 产品视觉参照：可穿戴与智能家居竞品 ──

  {
    discipline: '产品视觉参照',
    name: 'Garmin',
    url: 'https://www.garmin.com/en-US/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '运动健康可穿戴、GPS 手表、数据可视化、户外探险 lifestyle、航空/航海仪表',
    notes: '产品视觉参照；运动健康可穿戴和数据可视化标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Oura Ring',
    url: 'https://ouraring.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '健康指环、睡眠与身体数据、穿戴式传感器、极简产品设计、数据叙事',
    notes: '产品视觉参照；可穿戴健康数据叙事和极简产品设计标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Whoop',
    url: 'https://www.whoop.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '运动健康数据订阅、strain/recovery/sleep 可视化、运动员 lifestyle',
    notes: '产品视觉参照；健康数据订阅模式和运动科学可视化标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Roborock',
    url: 'https://www.roborock.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '扫地机器人、激光导航、智能避障、自清洁技术、家居场景',
    notes: '产品视觉参照；清洁机器人竞品，与 Dreame 对照；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Ecovacs',
    url: 'https://www.ecovacs.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '扫地机器人、擦窗机器人、智能家居清洁、全屋智能、产品矩阵',
    notes: '产品视觉参照；清洁机器人竞品，与 Dreame/Roborock 对照；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  // ── 行业媒体补充：ZEISS / Boston Scientific / Xylem ──
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'Physics World - Optics & Photonics',
    url: 'https://physicsworld.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '光学、光子学、激光技术、量子光学和物理研究可视化配图',
    strategyHint: 'Physics World 含高端物理学可视化；优先保留含显微镜成像、光学系统和光子芯片图的文章',
    notes: '行业媒体补充：ZEISS 光学技术第三方报道来源',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'Optics.org News',
    url: 'https://optics.org/news/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '光电子、激光、光学元件、光子集成电路和工业光学应用场景图',
    strategyHint: 'optics.org 是光电子行业权威媒体；优先保留含光刻、显微镜和光学设备图',
    notes: '行业媒体补充：ZEISS 光电子行业第三方报道来源',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'Semiconductor Engineering',
    url: 'https://semiengineering.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '半导体制造、光刻、晶圆检测、芯片设计和制造设备场景图',
    strategyHint: 'semiengineering.com 含半导体设备和制程技术图；优先保留含光刻机、检测设备的技术文章配图',
    notes: '行业媒体补充：ZEISS/ASML 半导体技术第三方报道来源',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Medical Design Outsourcing',
    url: 'https://www.medicaldesignandoutsourcing.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '介入医疗器械、植入设备、导管技术、手术器械和医疗设备制造场景图',
    strategyHint: '医疗器械行业媒体；优先保留含产品图、设备渲染和临床场景的报道',
    notes: '行业媒体补充：Boston Scientific 医疗器械行业第三方报道来源',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'WaterWorld News',
    url: 'https://www.waterworld.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '水处理、泵站、管网、水资源管理和水务数字化场景图',
    strategyHint: '水务行业媒体；优先保留含工程现场、设备和基础设施的可视化报道',
    notes: '行业媒体补充：Xylem 水务技术第三方报道来源',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Water Tech Online',
    url: 'https://www.watertechonline.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '工业水处理、水循环技术、废水处理和水利装备场景图',
    strategyHint: '水技术专业媒体；优先保留含水处理设备和场景图的文章',
notes: '行业媒体补充：Xylem 水技术第三方报道补充来源',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'Physics World - ZEISS Search',
    url: 'https://physicsworld.com/?s=zeiss',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'ZEISS显微镜、光学系统、电子显微镜和半导体光刻技术相关的物理学可视化',
    strategyHint: 'Physics World 站内搜索 ZEISS 结果页；优先保留含光学显微成像和显微镜技术图的文章',
    notes: 'ZEISS 精准补充：Physics World 搜索页共11篇ZEISS相关文章',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'Laser Focus World - ZEISS Search',
    url: 'https://www.laserfocusworld.com/?s=zeiss',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'ZEISS激光、光学元件和光子学产品技术报道配图',
    strategyHint: 'Laser Focus World 站内搜索 ZEISS；优先保留含光学镜头和激光系统配图的文章',
    notes: 'ZEISS 精准补充：光电子行业媒体站内搜索',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'SPIE - ZEISS Search',
    url: 'https://spie.org/search?term=zeiss',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'ZEISS光学工程、光子学器件和显微成像科研报道配图',
    strategyHint: 'SPIE 站内搜索 ZEISS；优先保留光学工程和光子学应用图',
    notes: 'ZEISS 精准补充：国际光学工程学会站内搜索',
  },
];

export function getActiveStaticEnterpriseSources(): EnterpriseSourceConfig[] {
  return ENTERPRISE_SOURCES.filter(source =>
    source.sourceType === 'enterprise'
    && source.category === 'ENT'
    && source.crawlTier === 'B'
    && source.crawlStatus === 'active_static'
    && source.adapterType === 'static_html'
  );
}

/**
 * Seed enterprise benchmark sources into the CrawlSource table.
 * Uses name+url lookup to avoid duplicate inserts and refresh mutable fields.
 */
export async function seedEnterpriseSources(): Promise<{ created: number; updated: number; unchanged: number; disabledStale: number }> {
  let created = 0;
  let updated = 0;
  let unchanged = 0;
  let disabledStale = 0;
  const configuredKeys = new Set(ENTERPRISE_SOURCES.map(config => `${config.name}\n${config.url}`));

  for (const config of ENTERPRISE_SOURCES) {
    const data = {
      name: config.name,
      url: config.url,
      sourceType: config.sourceType,
      category: config.category,
      crawlTier: config.crawlTier,
      crawlStatus: config.crawlStatus,
      adapterType: config.adapterType,
      visualValue: config.visualValue,
      strategyHint: config.strategyHint || '产品视觉参照；优先采官方产品页、解决方案页或场景化营销页，必要时使用 browser_render 或受控 URL 清单',
      notes: config.notes,
      enabled: true,
    };

    const existing = await prisma.crawlSource.findFirst({
      where: { name: config.name, url: config.url },
    });

    if (existing) {
      const hasChanges = existing.sourceType !== data.sourceType
        || existing.category !== data.category
        || existing.crawlTier !== data.crawlTier
        || existing.crawlStatus !== data.crawlStatus
        || existing.adapterType !== data.adapterType
        || existing.visualValue !== data.visualValue
        || existing.strategyHint !== data.strategyHint
        || existing.notes !== data.notes
        || existing.enabled !== data.enabled;

      if (hasChanges) {
        await prisma.crawlSource.update({
          where: { id: existing.id },
          data,
        });
        updated++;
      } else {
        unchanged++;
      }
      continue;
    }

    await prisma.crawlSource.create({
      data,
    });
    created++;
  }

  const staleSources = await prisma.crawlSource.findMany({
    where: { sourceType: 'enterprise', category: 'ENT', enabled: true },
  });
  for (const source of staleSources) {
    if (configuredKeys.has(`${source.name}\n${source.url}`)) continue;
    await prisma.crawlSource.update({
      where: { id: source.id },
      data: {
        enabled: false,
        crawlStatus: source.crawlStatus === 'active_static' ? 'manual' : source.crawlStatus,
        strategyHint: source.strategyHint
          ? `${source.strategyHint}；已从当前企业来源配置中移除，保留历史记录`
          : '已从当前企业来源配置中移除，保留历史记录',
      },
    });
    disabledStale++;
  }

  return { created, updated, unchanged, disabledStale };
}

async function main() {
  console.log('Seeding enterprise benchmark sources...');
  const result = await seedEnterpriseSources();
  console.log(`Done. Created: ${result.created}, Updated: ${result.updated}, Unchanged: ${result.unchanged}, Disabled stale: ${result.disabledStale}`);
}

const isMainModule = process.argv[1]?.endsWith('enterpriseSources.ts') || process.argv[1]?.endsWith('enterpriseSources.js');
if (isMainModule) {
  main()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seed failed:', err);
      process.exit(1);
    });
}
