/**
 * Enterprise benchmark source configurations.
 *
 * These sources map SJTU discipline directions to official enterprise case,
 * solution, product, technology, project, or newsroom pages with reusable
 * science/engineering visuals. Commercial translation pages are preferred over
 * generic news because the enterprise group is a benchmark for how research and
 * engineering outcomes become market-facing value.
 */
import { prisma } from '../prisma.js';

export interface EnterpriseSourceConfig {
  discipline: string;
  name: string;
  url: string;
  sourceType: string;
  category: string;
  crawlTier: string;
  crawlStatus: string;
  adapterType: string;
  visualValue: string;
  strategyHint?: string;
  notes: string;
  commercialIntent?: string;
  commercialPriority?: 'primary' | 'secondary' | 'fallback';
}

export const ENTERPRISE_SOURCES: EnterpriseSourceConfig[] = [
  {
    discipline: '船舶海洋与建筑工程学院',
    name: 'Kongsberg Maritime',
    url: 'https://www.kongsbergmaritime.com/products/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '船舶海洋装备、自动化船桥、声呐、海洋工程系统和海试场景图',
    strategyHint: '优先抓 products 入口；已验证可静态发现 bridge systems、propulsion、simulation 等产品页并入库',
    notes: 'discipline=船舶海洋与建筑工程学院；挪威海事技术头部企业；2026-06-03 产品页真实入库 11 条',
  },
  {
    discipline: '船舶海洋与建筑工程学院',
    name: 'Arup Projects',
    url: 'https://www.arup.com/projects/all-projects/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '建筑工程、基础设施、桥梁、城市韧性和工程项目案例图',
    strategyHint: '静态 fetch 返回 500；使用 enterprise:browser-batch 渲染 projects 列表可入库项目图',
    notes: 'discipline=船舶海洋与建筑工程学院；国际工程咨询与建筑工程设计标杆；2026-06-03 browser_render 入库 3 条',
  },
  {
    discipline: '船舶海洋与建筑工程学院',
    name: 'Autodesk Newsroom',
    url: 'https://adsknews.autodesk.com/en/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '建筑工程数字化、BIM、施工管理、产品设计与制造、数字孪生、AI/ML 工作流配图、客户项目案例图',
    strategyHint: 'WordPress 站点，支持静态发现；customer-stories 有 bot 防护改用 newsroom 入口',
    notes: 'discipline=船舶海洋与建筑工程学院；Autodesk 官方 newsroom；AEC/PD&M/创新/可持续发展/客户故事栏目；commercialIntent=customer_story；2026-06-03 因 customer-stories bot拦截改用 newsroom',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Siemens Energy',
    url: 'https://www.siemens-energy.com/global/en/home/press-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '燃机、氢能、储能、电网设备、能源系统工程图和工厂场景',
    strategyHint: '静态发现当前为 0 链接；需改 stories/solutions 入口或 browser_render',
    notes: 'discipline=机械与动力工程学院；能源动力系统头部企业',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Rolls-Royce',
    url: 'https://www.rolls-royce.com/media/press-releases.aspx',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '航空发动机、船舶动力、核动力、小型模块堆和工程制造场景图',
    strategyHint: '优先抓 press releases；创新和产品服务页面作为补充入口',
    notes: 'discipline=机械与动力工程学院；动力系统与航空发动机标杆',
  },
  {
    discipline: '机械与动力工程学院',
    name: 'Caterpillar News',
    url: 'https://www.cat.com/en_US/articles/customer-stories.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '工程机械、动力系统、矿山设备、施工装备和自动化作业场景图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或更稳定的 customer story 列表入口',
    notes: 'discipline=机械与动力工程学院；工程机械和动力装备商业化应用案例来源；commercialIntent=customer_story；2026-06-03 static fetch failed',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'Huawei News',
    url: 'https://www.huawei.com/en/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '通信设备、网络基础设施、终端产品、ICT 技术图和研发场景',
    strategyHint: 'news 列表静态抓取不足；可用人工提供的 consumer wearable / 产品营销页作为受控 URL 清单补充',
    notes: 'discipline=电子信息与电气工程学院；ICT 与通信设备头部企业；2026-06-03 用户提供 wearable 页面入库 5 条',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'Qualcomm OnQ',
    url: 'https://www.qualcomm.com/news/onq',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '移动通信、射频、芯片平台、AI 终端和无线技术解释图',
    strategyHint: 'OnQ 列表静态发现不足；可用 AI research / Snapdragon 产品详情页做受控 URL 清单入库',
    notes: 'discipline=电子信息与电气工程学院；无线通信与移动芯片标杆；2026-06-03 替代详情页入库 2 条',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Technical Blog',
    url: 'https://developer.nvidia.com/blog',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: 'GPU、AI 计算、通信加速、仿真、数据中心和技术架构图',
    strategyHint: '保留 technical blog 中模型图、架构图、性能图和硬件平台图；商业化样本优先由 NVIDIA Customer Stories 补充',
    notes: 'discipline=电子信息与电气工程学院；AI 计算与电子信息技术解释来源；commercialIntent=technical_explanation',
    commercialIntent: 'technical_explanation',
    commercialPriority: 'secondary',
  },
  {
    discipline: '电子信息与电气工程学院',
    name: 'NVIDIA Customer Stories',
    url: 'https://www.nvidia.com/en-us/case-studies/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: 'AI、GPU、仿真、数字孪生、机器人和行业解决方案的客户案例图、性能图和产品场景图',
    strategyHint: '优先抓 case studies；重点保留行业应用、性能提升、解决方案架构和产品落地场景',
    notes: 'discipline=电子信息与电气工程学院；AI 计算商业化落地案例来源；commercialIntent=case_study',
    commercialIntent: 'case_study',
    commercialPriority: 'primary',
  },
  {
    discipline: '电气工程学院',
    name: 'ABB News',
    url: 'https://new.abb.com/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '电气化、变频器、机器人、工业自动化、电网和工厂场景图',
    strategyHint: '优先抓 news；按 electrification / robotics 主题页细分二阶段优化',
    notes: 'discipline=电气工程学院；电气与自动化跨学科头部企业',
  },
  {
    discipline: '电气工程学院',
    name: 'Schneider Electric Newsroom',
    url: 'https://www.se.com/us/en/about-us/newsroom/news/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '配电、能效管理、楼宇电气、数据中心基础设施和工业能源图',
    strategyHint: '优先抓 newsroom press releases；已通过真实小批量采集，继续保留工程设备、电气基础设施和楼宇系统图',
    notes: 'discipline=电气工程学院；能源管理与电气自动化标杆',
  },
  {
    discipline: '电气工程学院',
    name: 'Eaton News Releases',
    url: 'https://www.eaton.com/us/en-us/company/news-insights/news-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '配电、储能、数据中心电气、工业电气设备和能源管理场景图',
    strategyHint: '优先抓 news releases；保留电气设备、能源基础设施和应用案例图',
    notes: 'discipline=电气工程学院；电气设备与能源管理标杆补充来源',
  },
  {
    discipline: '自动化与感知学院',
    name: 'Boston Dynamics Blog',
    url: 'https://bostondynamics.com/blog/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '机器人实物、移动感知、控制系统、产品演示和视频封面图',
    strategyHint: '优先抓 blog；视频页面仅取 poster/og:image，不抓视频本体',
    notes: 'discipline=自动化与感知学院；移动机器人和感知控制标杆',
  },
  {
    discipline: '自动化与感知学院',
    name: 'FANUC America News',
    url: 'https://www.fanucamerica.com/news-resources/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '工业机器人、自动化产线、机床控制、工厂应用案例图',
    strategyHint: '优先抓 news-resources/news；若列表分页动态化则标注 browser_render',
    notes: 'discipline=自动化与感知学院；工业机器人与数控自动化标杆',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Google Research Blog',
    url: 'https://research.google/blog/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'static_html',
    visualValue: 'AI 研究图、模型示意、数据可视化、交互系统和计算机视觉案例',
    strategyHint: '仅作为企业研究视觉补充；商业化参照优先抓 customer stories、product/solution pages 和行业应用页',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；企业研究视觉补充，不作为商业化优先入口；commercialIntent=research_supplement',
    commercialIntent: 'research_supplement',
    commercialPriority: 'fallback',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Microsoft AI Customer Stories',
    url: 'https://www.microsoft.com/ai/ai-customer-stories',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: 'AI 客户案例、行业应用、业务成效、产品能力和解决方案架构图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或替代公开 customer story 入口',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；AI 商业化客户案例来源；commercialIntent=customer_story',
    commercialIntent: 'customer_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '计算机学院（网络空间安全学院、密码学院）',
    name: 'Microsoft AI Co-Innovation Labs',
    url: 'https://aiotlabs.microsoft.com/en/case-studies',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: 'AI 原型、行业解决方案、技术组合、客户成果和实验室共创案例图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或替代公开 case studies 入口',
    notes: 'discipline=计算机学院（网络空间安全学院、密码学院）；AI 共创商业化案例来源；commercialIntent=case_study',
    commercialIntent: 'case_study',
    commercialPriority: 'primary',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'ASML News',
    url: 'https://www.asml.com/en/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '光刻机、洁净室、半导体制造设备、技术解释图和工业摄影',
    strategyHint: '优先抓 news；technology 页面作为二阶段补充',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；半导体装备头部企业',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'TSMC Newsroom',
    url: 'https://pr.tsmc.com/english/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'manual',
    visualValue: '晶圆厂、先进制程、封装、半导体制造和研发新闻图',
    strategyHint: '优先抓 PR newsroom；若静态列表不足，后续改 browser_render',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；晶圆制造头部企业',
  },
  {
    discipline: '集成电路学院（信息与电子工程学院）',
    name: 'Arm Newsroom',
    url: 'https://www.arm.com/company/success-library/arm-designs/powercast',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '芯片 IP、AI 计算、边缘处理器、半导体生态、客户成功案例和应用场景图',
    strategyHint: '静态 fetch 当前失败；需 browser_render 或更稳定的 success library 列表入口',
    notes: 'discipline=集成电路学院（信息与电子工程学院）；芯片架构与半导体 IP 商业化案例来源；commercialIntent=success_story；2026-06-03 static fetch failed',
    commercialIntent: 'success_story',
    commercialPriority: 'primary',
  },
  {
    discipline: '材料科学与工程学院',
    name: 'BASF News',
    url: 'https://www.basf.com/global/en/media/news-releases',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '化工材料、实验室、工厂、分子材料和应用产品图',
    strategyHint: '优先抓 news releases；research press 图文适合作为材料视觉案例',
    notes: 'discipline=材料科学与工程学院；化工材料头部企业',
  },
  {
    discipline: '材料科学与工程学院',
    name: 'Corning News',
    url: 'https://www.corning.com/worldwide/en/about-us/news-events/news-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '玻璃、陶瓷、光纤、先进材料、实验制造和产品微观结构图',
    strategyHint: '优先抓 news releases；innovation 页面作为二阶段补充',
    notes: 'discipline=材料科学与工程学院；先进玻璃陶瓷与光学材料标杆',
  },
  {
    discipline: '材料科学与工程学院',
    name: 'Dow Press Releases',
    url: 'https://corporate.dow.com/en-us/news/press-releases.html',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'manual',
    visualValue: '材料科学、低碳材料、包装材料、热管理材料、实验室和应用场景图',
    strategyHint: '官网静态入口真实采集会落到 HTTP 403 或品牌页；不绕过，后续改用人工采集或替代材料企业入口',
    notes: 'discipline=材料科学与工程学院；材料科学与化工材料标杆补充来源',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Xylem Newsroom',
    url: 'https://www.xylem.com/en-us/about-xylem/newsroom/press-releases/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '水处理、水资源监测、泵站、传感器和环境工程案例图',
    strategyHint: '优先抓 applications / watermark 等可静态入库页面；press releases 作为二阶段入口继续调优',
    notes: 'discipline=环境科学与工程学院；水技术与环境工程头部企业；2026-06-03 真实小批量入库 10 条',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Veolia Newsroom',
    url: 'https://www.veolia.com/en/newsroom/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '水处理、废弃物资源化、环境服务、资源循环、低碳基础设施和工程案例图',
    strategyHint: '优先抓 newsroom news；保留 water、waste、energy、resource efficiency 和环境工程项目图',
    notes: 'discipline=环境科学与工程学院；环境服务与资源循环标杆补充来源',
  },
  {
    discipline: '环境科学与工程学院',
    name: 'Orsted News',
    url: 'https://orsted.com/en/media-centre/news',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'manual',
    visualValue: '海上风电、可再生能源、低碳基础设施和能源工程场景图',
    strategyHint: '优先抓 media-centre/news；注意筛掉投资者关系纯文本新闻',
    notes: 'discipline=环境科学与工程学院；可再生能源和海上风电标杆',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Siemens Healthineers',
    url: 'https://www.siemens-healthineers.com/medical-imaging',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '医学影像设备、诊断系统、医院场景、AI 医疗和设备渲染图',
    strategyHint: '优先抓 medical-imaging 入口；可静态发现 CT、MRI、超声和数字医疗产品页',
    notes: 'discipline=生物医学工程学院；医学影像与诊断设备头部企业；2026-06-03 产品页真实入库 8 条',
  },
  {
    discipline: '生物医学工程学院',
    name: 'GE HealthCare Press Releases',
    url: 'https://www.gehealthcare.com/en-us/about/newsroom/press-releases',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '医学影像设备、AI 医疗、核医学、MR/CT/超声系统、临床研究和医院场景图',
    strategyHint: 'dry-run 可提图，但 active-batch 静态发现不足；后续需改用 browser_render 或更细新闻 API',
    notes: 'discipline=生物医学工程学院；医学影像与医疗技术标杆补充来源，暂作调优候选',
  },
  {
    discipline: '生物医学工程学院',
    name: 'Boston Scientific Newsroom',
    url: 'https://news.bostonscientific.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '介入医疗器械、植入设备、临床应用、产品细节和医疗技术新闻图',
    strategyHint: '优先抓 newsroom releases；排除回购、投资、财报和栏目页，真实采集必须人工复核',
    notes: 'discipline=生物医学工程学院；介入医疗器械标杆补充来源',
  },
  {
    discipline: '航空航天学院',
    name: 'Airbus Newsroom',
    url: 'https://www.airbus.com/en/newsroom',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'active_static',
    adapterType: 'static_html',
    visualValue: '飞机、直升机、卫星、航天系统、飞行测试和工业制造图',
    strategyHint: '优先抓 newsroom；innovation 页面作为二阶段补充',
    notes: 'discipline=航空航天学院；航空航天系统头部企业',
  },
  {
    discipline: '航空航天学院',
    name: 'Boeing Newsroom',
    url: 'https://boeing.mediaroom.com/news-releases-statements',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'needs_adapter_tuning',
    adapterType: 'static_html',
    visualValue: '飞机、航天器、防务系统、制造装配、飞行测试和工程新闻图',
    strategyHint: '优先抓 mediaroom releases；产品图库和视频页不纳入第一轮',
    notes: 'discipline=航空航天学院；航空航天制造头部企业',
  },

  // ── 产品视觉参照：用户点名优先企业 ──

  {
    discipline: '产品视觉参照',
    name: 'Tesla Model Y',
    url: 'https://www.tesla.com/modely',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '电动车、极简产品叙事、交互 UI、场景化生活图、空气动力学设计渲染',
    strategyHint: '产品页，需 browser_render；优先取 hero 图、360 度车图、场景 lifestyle 图、UI 交互帧',
    notes: '产品视觉参照；电动车标杆；极简官网设计语言；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Tesla Cybertruck',
    url: 'https://www.tesla.com/cybertruck',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '赛博皮卡、未来感设计、材料质感、极端场景测试、工程能力可视化',
    notes: '产品视觉参照；极端工程美学和未来感设计标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Tesla Optimus',
    url: 'https://www.tesla.com/optimus',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '人形机器人、具身智能、工程细节摄影、制造场景、技术参数可视化',
    notes: '产品视觉参照；人形机器人产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Apple iPhone',
    url: 'https://www.apple.com/iphone/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '消费电子、材质特写、交互演示、色彩策略、产品 lifestyle 摄影',
    notes: '产品视觉参照；消费电子产品呈现全球标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Apple Vision Pro',
    url: 'https://www.apple.com/apple-vision-pro/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '空间计算、透明材质渲染、交互手势可视化、3D 产品分解图、沉浸体验场景',
    notes: '产品视觉参照；空间计算和沉浸感产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Apple Watch',
    url: 'https://www.apple.com/apple-watch/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '可穿戴设备、健康数据可视化、材质与配色展示、运动 lifestyle、表带设计',
    notes: '产品视觉参照；可穿戴设备 lifestyle 营销标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Unitree',
    url: 'https://www.unitree.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '四足与人形机器人、具身智能、运动控制、工程细节、产品矩阵展示',
    notes: '产品视觉参照；中国机器人企业产品呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Unitree G1',
    url: 'https://www.unitree.com/g1/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '人形机器人产品页、关节机构特写、动作序列、灵巧手演示',
    notes: '产品视觉参照；人形机器人单产品页面标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Unitree Go2',
    url: 'https://www.unitree.com/go2/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '四足机器人产品页、运动能力演示、户外场景、跟随交互、技术规格',
    notes: '产品视觉参照；四足机器人消费级产品页面标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Google Pixel 9',
    url: 'https://store.google.com/product/pixel_9',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'AI 手机、Gemini 整合、影像功能、材质与色彩、生活场景',
    notes: '产品视觉参照；AI 功能驱动的手机产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Google Phones',
    url: 'https://store.google.com/category/phones',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '手机全家桶、产品生态、功能对比、AI 卖点可视化',
    notes: '产品视觉参照；Google 设备生态产品对比页；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Google Watches',
    url: 'https://store.google.com/category/watches',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '智能手表、健康 tracking、生活方式、运动场景',
    notes: '产品视觉参照；可穿戴设备 lifestyle 展示页；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Xiaomi Global',
    url: 'https://www.mi.com/global/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '手机、IoT 生态、智能汽车、影像系统、小米生态链产品矩阵',
    notes: '产品视觉参照；中国消费电子和智能生态标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Xiaomi 15 Ultra',
    url: 'https://www.mi.com/global/product/xiaomi-15-ultra/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '影像旗舰手机、徕卡合作、镜头特写、摄影样张、材质细节',
    notes: '产品视觉参照；手机影像系统产品页标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Xiaomi Phone List',
    url: 'https://www.mi.com/global/product-list/phone/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '手机全家桶、产品线对比、色彩策略、系列化设计语言',
    notes: '产品视觉参照；消费者产品线和系列化呈现参考；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Dreame Tech',
    url: 'https://www.dreametech.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '清洁机器人、智能家居、机械结构展示、家居 lifestyle、产品系列',
    notes: '产品视觉参照；中国智能清洁机器人产品呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Dreame Robot Vacuums',
    url: 'https://www.dreametech.com/collections/robot-vacuums',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '扫地机器人产品线、激光导航、自动集尘、清洁能力可视化',
    notes: '产品视觉参照；清洁机器人品类产品矩阵展示页；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'secondary',
  },

  // ── 产品视觉参照：补充头部企业 ──

  {
    discipline: '产品视觉参照',
    name: 'DJI',
    url: 'https://www.dji.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '无人机、航拍影像、手持云台、运动相机、空中视角、产品细节',
    notes: '产品视觉参照；全球无人机和影像设备产品呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Dyson',
    url: 'https://www.dyson.com/en',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '高端家电、空气动力学、透明结构展示、CMF 设计、工程美学 lifestyle',
    notes: '产品视觉参照；工程驱动产品美学全球标杆；改用 /en 路径绕过 Cloudflare；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Samsung Mobile',
    url: 'https://www.samsung.com/us/smartphones/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '折叠屏、AI 手机、Galaxy 生态、显示技术、生活方式摄影',
    notes: '产品视觉参照；全球手机出货量第一企业的产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Sony Electronics',
    url: 'https://electronics.sony.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'blocked_cloudflare',
    adapterType: 'browser_render',
    visualValue: '影像、音频、娱乐硬件、传感器、产品 CMF、技术参数可视化',
    notes: '产品视觉参照；消费电子和影像传感器产品设计标杆；2026-06-03 electronics.sony.com 及 sony.com/en 均 Access Denied；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
    strategyHint: 'sony.com/en 集团门户和 electronics.sony.com 均返回 Access Denied；需真实浏览器带 header 或 CAPTCHA 方案',
  },
  {
    discipline: '产品视觉参照',
    name: 'Meta Quest',
    url: 'https://www.meta.com/quest/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'VR/MR 头显、空间交互、手柄设计、沉浸场景、混合现实体验',
    notes: '产品视觉参照；VR/MR 产品叙事和空间计算标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Meta Ray-Ban',
    url: 'https://www.meta.com/smart-glasses/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: 'AI 可穿戴、智能眼镜、生活方式融合、第一人称视角、时尚+科技',
    notes: '产品视觉参照；AI 可穿戴设备时尚化呈现标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },

  // ── 产品视觉参照：汽车与机器人扩展 ──

  {
    discipline: '产品视觉参照',
    name: 'BYD Global',
    url: 'https://www.byd.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '新能源汽车、刀片电池、智能座舱、车规芯片、全球化品牌',
    notes: '产品视觉参照；中国新能源汽车全球销量第一的企业产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'NIO',
    url: 'https://www.nio.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '高端电动车、换电技术、NIO House lifestyle、自动驾驶可视化、设计语言',
    notes: '产品视觉参照；中国高端电动车 lifestyle 营销标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'XPeng',
    url: 'https://www.xpeng.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '智能驾驶、飞行汽车、机器人、智能座舱、OTA 技术可视化',
    notes: '产品视觉参照；智能驾驶和飞行汽车技术产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Rivian',
    url: 'https://rivian.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '户外电动车、冒险 lifestyle、露营场景、环保材料、制造工程图',
    notes: '产品视觉参照；户外冒险生活方式驱动的电动车品牌标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Figure AI',
    url: 'https://www.figure.ai/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '人形机器人、具身智能、灵巧手、工业应用、技术愿景叙事',
    notes: '产品视觉参照；人形机器人创业公司产品叙事标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Agility Robotics',
    url: 'https://agilityrobotics.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '工业人形机器人、物流应用、仓库场景、Digital Twin、安全设计',
    notes: '产品视觉参照；工业人形机器人商用化产品标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },

  // ── 产品视觉参照：可穿戴与智能家居竞品 ──

  {
    discipline: '产品视觉参照',
    name: 'Garmin',
    url: 'https://www.garmin.com/en-US/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '运动健康可穿戴、GPS 手表、数据可视化、户外探险 lifestyle、航空/航海仪表',
    notes: '产品视觉参照；运动健康可穿戴和数据可视化标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Oura Ring',
    url: 'https://ouraring.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '健康指环、睡眠与身体数据、穿戴式传感器、极简产品设计、数据叙事',
    notes: '产品视觉参照；可穿戴健康数据叙事和极简产品设计标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Whoop',
    url: 'https://www.whoop.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '运动健康数据订阅、strain/recovery/sleep 可视化、运动员 lifestyle',
    notes: '产品视觉参照；健康数据订阅模式和运动科学可视化标杆；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Roborock',
    url: 'https://www.roborock.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '扫地机器人、激光导航、智能避障、自清洁技术、家居场景',
    notes: '产品视觉参照；清洁机器人竞品，与 Dreame 对照；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
  {
    discipline: '产品视觉参照',
    name: 'Ecovacs',
    url: 'https://www.ecovacs.com/',
    sourceType: 'enterprise',
    category: 'ENT',
    crawlTier: 'B',
    crawlStatus: 'manual',
    adapterType: 'browser_render',
    visualValue: '扫地机器人、擦窗机器人、智能家居清洁、全屋智能、产品矩阵',
    notes: '产品视觉参照；清洁机器人竞品，与 Dreame/Roborock 对照；commercialIntent=product_page',
    commercialIntent: 'product_page',
    commercialPriority: 'primary',
  },
];

export function getActiveStaticEnterpriseSources(): EnterpriseSourceConfig[] {
  return ENTERPRISE_SOURCES.filter(source =>
    source.sourceType === 'enterprise'
    && source.category === 'ENT'
    && source.crawlTier === 'B'
    && source.crawlStatus === 'active_static'
    && source.adapterType === 'static_html'
  );
}

/**
 * Seed enterprise benchmark sources into the CrawlSource table.
 * Uses name+url lookup to avoid duplicate inserts and refresh mutable fields.
 */
export async function seedEnterpriseSources(): Promise<{ created: number; updated: number; unchanged: number; disabledStale: number }> {
  let created = 0;
  let updated = 0;
  let unchanged = 0;
  let disabledStale = 0;
  const configuredKeys = new Set(ENTERPRISE_SOURCES.map(config => `${config.name}\n${config.url}`));

  for (const config of ENTERPRISE_SOURCES) {
    const data = {
      name: config.name,
      url: config.url,
      sourceType: config.sourceType,
      category: config.category,
      crawlTier: config.crawlTier,
      crawlStatus: config.crawlStatus,
      adapterType: config.adapterType,
      visualValue: config.visualValue,
      strategyHint: config.strategyHint || '产品视觉参照；优先采官方产品页、解决方案页或场景化营销页，必要时使用 browser_render 或受控 URL 清单',
      notes: config.notes,
      enabled: true,
    };

    const existing = await prisma.crawlSource.findFirst({
      where: { name: config.name, url: config.url },
    });

    if (existing) {
      const hasChanges = existing.sourceType !== data.sourceType
        || existing.category !== data.category
        || existing.crawlTier !== data.crawlTier
        || existing.crawlStatus !== data.crawlStatus
        || existing.adapterType !== data.adapterType
        || existing.visualValue !== data.visualValue
        || existing.strategyHint !== data.strategyHint
        || existing.notes !== data.notes
        || existing.enabled !== data.enabled;

      if (hasChanges) {
        await prisma.crawlSource.update({
          where: { id: existing.id },
          data,
        });
        updated++;
      } else {
        unchanged++;
      }
      continue;
    }

    await prisma.crawlSource.create({
      data,
    });
    created++;
  }

  const staleSources = await prisma.crawlSource.findMany({
    where: { sourceType: 'enterprise', category: 'ENT', enabled: true },
  });
  for (const source of staleSources) {
    if (configuredKeys.has(`${source.name}\n${source.url}`)) continue;
    await prisma.crawlSource.update({
      where: { id: source.id },
      data: {
        enabled: false,
        crawlStatus: source.crawlStatus === 'active_static' ? 'manual' : source.crawlStatus,
        strategyHint: source.strategyHint
          ? `${source.strategyHint}；已从当前企业来源配置中移除，保留历史记录`
          : '已从当前企业来源配置中移除，保留历史记录',
      },
    });
    disabledStale++;
  }

  return { created, updated, unchanged, disabledStale };
}

async function main() {
  console.log('Seeding enterprise benchmark sources...');
  const result = await seedEnterpriseSources();
  console.log(`Done. Created: ${result.created}, Updated: ${result.updated}, Unchanged: ${result.unchanged}, Disabled stale: ${result.disabledStale}`);
}

const isMainModule = process.argv[1]?.endsWith('enterpriseSources.ts') || process.argv[1]?.endsWith('enterpriseSources.js');
if (isMainModule) {
  main()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seed failed:', err);
      process.exit(1);
    });
}
