export interface StaticSourceAdapter {
  name: string;
  hostPatterns: RegExp[];
  articleLinkSelectors: string[];
  articlePathPatterns: RegExp[];
  excludeUrlPatterns: RegExp[];
  excludeTitlePatterns?: RegExp[];
  contentSelectors: string[];
  titleSelectors: string[];
  imageSelectors: string[];
  excludeSelectors: string[];
}

const COMMON_EXCLUDE_SELECTORS = [
  'nav', 'header', 'footer', 'aside', 'form',
  '[role="navigation"]', '[aria-label*="share" i]', '[aria-label*="comment" i]',
  '.nav', '.navbar', '.menu', '.breadcrumb', '.breadcrumbs',
  '.share', '.social', '.related', '.recommend', '.advertisement', '.ads',
  '.newsletter', '.subscribe', '.cookie', '.promo',
  '.comments', '.comment-section', '.disqus', '[id^="disqus"]',
  '.gtm', '.googletagmanager', '.analytics', '.tracking',
  '[data-nosnippet]', '.hidden', '.sr-only',
  '.consent-banner', '.gdpr', '.cc-banner',
];

const ENTERPRISE_EXCLUDE_SELECTORS = [
  ...COMMON_EXCLUDE_SELECTORS,
  '.cookie-banner', '.cookie-consent', '.modal', '.overlay',
  '.language-selector', '.site-search', '.mega-menu',
  '.hero__cta', '.cta', '.campaign', '.market-selector',
  '.stock-ticker', '.investor', '.financial-calendar',
];

export const STATIC_SOURCE_ADAPTERS: StaticSourceAdapter[] = [
  {
    name: 'MIT News',
    hostPatterns: [/^news\.mit\.edu$/i],
    articleLinkSelectors: [
      'article a[href]',
      '.view-content a[href]',
      '.page-term--views a[href]',
      'h2 a[href], h3 a[href]',
    ],
    articlePathPatterns: [/\/\d{4}\//, /\/topic\/research/i],
    excludeUrlPatterns: [/\/rss-/, /\/clp\//i, /\/school\//i],
    contentSelectors: ['article', '.news-article', '.article-body', '.field-name-body', 'main'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.field-name-field-image img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'Harvard Gazette',
    hostPatterns: [/^news\.harvard\.edu$/i],
    articleLinkSelectors: [
      'article a[href]',
      '.post-card a[href]',
      '.story-card a[href]',
      'h2 a[href], h3 a[href]',
    ],
    articlePathPatterns: [/\/gazette\/story\//i, /\/gazette\//i],
    excludeUrlPatterns: [],
    contentSelectors: ['article', '.article-content', '.entry-content', '.story-content', 'main'],
    titleSelectors: ['h1', '.article-title', '.entry-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.wp-block-image img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'Berkeley Lab News Center',
    hostPatterns: [/^newscenter\.lbl\.gov$/i],
    articleLinkSelectors: [
      'article a[href]',
      '.post a[href]',
      '.entry-title a[href]',
      'h2 a[href], h3 a[href]',
    ],
    articlePathPatterns: [/\/\d{4}\/\d{2}\/\d{2}\//, /\/news\//i],
    excludeUrlPatterns: [/\/all-news\//i, /[?&]type=qa/i],
    contentSelectors: ['article', '.entry-content', '.post-content', '.article-content', 'main'],
    titleSelectors: ['h1', '.entry-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.wp-block-image img', '.entry-content img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'Stanford Engineering',
    hostPatterns: [/^engineering\.stanford\.edu$/i],
    articleLinkSelectors: [
      'article a[href]',
      '.views-row a[href]',
      '.card a[href]',
      '.teaser a[href]',
      'h2 a[href], h3 a[href]',
      'a[href*="/news/"]',
    ],
    articlePathPatterns: [/\/news\//i, /\/magazine\//i],
    excludeUrlPatterns: [/\/people\//i, /\/departments\//i, /\/events\//i],
    contentSelectors: ['article', '.node__content', '.field--name-body', '.content', 'main'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.field--name-field-media-image img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'NCI Visuals Online',
    hostPatterns: [/^visualsonline\.cancer\.gov$/i],
    articleLinkSelectors: [
      'a[href*="details.cfm"]',
      'a[href*="imageid="]',
      'h2 a[href], h3 a[href]',
    ],
    articlePathPatterns: [/details\.cfm\?imageid=/i, /searchaction\.cfm/i],
    excludeUrlPatterns: [/retrieveattachment\.cfm/i, /cart/i],
    contentSelectors: ['main', 'article', 'body'],
    titleSelectors: ['h1', 'h2', 'title'],
    imageSelectors: ['img[src*="retrieve"]', 'img[alt*="preview" i]', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'NOAA Digital Collections',
    hostPatterns: [
      /^prod-01-alb-www-noaa\.woc\.noaa\.gov$/i,
      /^www\.noaa\.gov$/i,
      /^noaa\.gov$/i,
      /^pmel\.noaa\.gov$/i,
      /^www\.pmel\.noaa\.gov$/i,
    ],
    articleLinkSelectors: [
      'article a[href]',
      '.views-row a[href]',
      '.card a[href]',
      'h2 a[href], h3 a[href]',
      'a[href*="/media/digital-collections-photo/"]',
      'a[href*="/digital-collections/collections/photo-library/"]',
    ],
    articlePathPatterns: [
      /\/media\/digital-collections-photo\//i,
      /\/digital-collections\/collections\/photo-library\//i,
      /\/gallery\//i,
    ],
    excludeUrlPatterns: [/\/about\//i, /\/contact\//i],
    contentSelectors: ['article', 'main', '.region-content', '.content', 'body'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main img', '.content img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'Max Planck Society',
    hostPatterns: [/^www\.mpg\.de$/i, /^mpg\.de$/i],
    articleLinkSelectors: [
      'article a[href]',
      '.teaser a[href]',
      '.news-list a[href]',
      'a[href*="/research/"]',
      'a[href*="/press-release/"]',
      'a[href*="/news/"]',
      'h2 a[href], h3 a[href]',
    ],
    articlePathPatterns: [/\/\d{7,}/, /\/research\//i, /\/press-release\//i, /\/news\//i],
    excludeUrlPatterns: [],
    contentSelectors: ['article', '.content', '.main-content', '.article-content', 'main'],
    titleSelectors: ['h1', '.headline', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.content img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'CAS Research Progress',
    hostPatterns: [/^www\.cas\.cn$/i, /^cas\.cn$/i],
    articleLinkSelectors: [
      'ul.kyjz_list a[href]',
      'div.model_r ul.kyjz_list a[href]',
      '.xl_bt a[href]',
      'a[href*="/syky/"]',
      'a[href*="/cg/zh/"]',
    ],
    articlePathPatterns: [/\/syky\//i, /\/cg\/zh\//i, /\/kx\/gz\//i, /\/t\d{8}_\d+\.shtml$/],
    excludeUrlPatterns: [/\/index\.shtml$/i, /\/syky\/$/],
    contentSelectors: ['div.TRS_UEDITOR', 'div.trs_editor_view', 'div.xl_content', 'div.xl', 'div#_content', 'main'],
    titleSelectors: ['h2.xl_title', 'meta[name="ArticleTitle"]', 'h1', 'title'],
    imageSelectors: ['div.TRS_UEDITOR img', 'div.xl_content img', 'div.xl_content video[poster]', 'div.xl img', 'main img'],
    excludeSelectors: [
      ...COMMON_EXCLUDE_SELECTORS,
      '.top1', '.top2', '.nav', '.nav_model',
      '.m_search', '.station2',
      '.xl_title2', '.xl_bottom',
      '.xfbb', '.bdsharebuttonbox', '.share',
      '.fontB', '.fontM', '.fontS',
      '.search', '.ser_ipt', '.ser_btn',
      '.wllink_cent',
    ],
  },
  {
    name: 'ScienceNet',
    hostPatterns: [/^news\.sciencenet\.cn$/i, /^sciencenet\.cn$/i, /^www\.sciencenet\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/htmlnews/"]',
      'ul li a[href]',
      '.boxm a[href]',
      '.Black a[href]',
      '.newrlist1 a[href], .newrlist2 a[href]',
      'h2 a[href], h3 a[href]',
    ],
    articlePathPatterns: [/\/htmlnews\//i, /\/html\//i, /\/news\//i, /\/paper\//i, /\/\d{4}\/\d+\/\d+\.shtm/i],
    excludeUrlPatterns: [/\/morenews/, /\/fieldlist/, /\/topnews/, /\/imgnews/, /\/indexyaowen/],
    contentSelectors: ['article', '.article_content', '.news_content', '.content', 'main', '#content', '.main'],
    titleSelectors: ['h1', '.article_title', 'title'],
    imageSelectors: ['article figure img', 'article img', '.article_content img', '.news_content img', '.main img', '#content img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'Tsinghua Research',
    hostPatterns: [/^www\.tsinghua\.edu\.cn$/i, /^tsinghua\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/info/"]',
      '.AcademicTh ul a[href]',
      '.text a[href]',
      'h4 a[href]',
    ],
    articlePathPatterns: [/\/info\/\d+\/\d+\.htm/i],
    excludeUrlPatterns: [/\/kxyj\.htm/i, /\/index\.htm/i],
    contentSelectors: ['#vsb_content_1001', '.v_news_content', '.content', 'main', 'article'],
    titleSelectors: ['.bt', '.nry_bt .bt', 'h1', 'title'],
    imageSelectors: ['.v_news_content img', '.content img', '.v_news_content img.img_vsb_content'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: 'PKU Research',
    hostPatterns: [/^news\.pku\.edu\.cn$/i, /^pku\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/jxky/"]',
      '.research a[href]',
      '.research-info a[href]',
      'h3 a[href]',
    ],
    articlePathPatterns: [/\/jxky\//i, /\/xwzh\//i],
    excludeUrlPatterns: [/\/index\.htm$/i],
    contentSelectors: ['.article', '.article-content', '#content', 'main'],
    titleSelectors: ['.articleTitle h3', 'h3', 'h1', 'title'],
    imageSelectors: ['.article img', '.article-content img', '#content img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  // ===== Domestic university expansion (7 new sources) =====
  {
    name: '浙江大学-求是新闻网',
    hostPatterns: [/^www\.news\.zju\.edu\.cn$/i, /^news\.zju\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/xs/list.htm"]',
      'a[href*=".zju.edu.cn"]',
      'ul.list-a a[href]',
      '.list a[href]',
      'h3 a[href], h4 a[href]',
      'a[href*="/c/"]',
    ],
    articlePathPatterns: [/\/\d{4}\/\d{4}\/c\//i, /\/xs\//i, /\/c\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/list\.htm$/i, /\/rss\//i],
    contentSelectors: ['#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['h1', '.bt', '.article-title', 'title'],
    imageSelectors: ['.v_news_content img', '.TRS_Editor img', '.content img', 'article img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '哈尔滨工业大学-新闻网',
    hostPatterns: [/^news\.hit\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/"]',
      'ul.news-list a[href]',
      '.list a[href]',
      'h3 a[href], h4 a[href]',
      'a[href*="/c/"]',
    ],
    articlePathPatterns: [/\/\d{4}\/\d{4}\/c\//i, /\/article\//i, /\/content\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/list\.htm$/i, /\/rss\//i],
    contentSelectors: ['#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['h1', '.bt', '.article-title', 'title'],
    imageSelectors: ['.v_news_content img', '.TRS_Editor img', '.content img', 'article img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '华中科技大学-新闻网',
    hostPatterns: [/^news\.hust\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/info/"]',
      'ul.list a[href]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/info\/\d+\/\d+\.htm/i, /\/content\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/info\/1003\/$/i],
    contentSelectors: ['#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['h1', '.bt', '.article-title', 'title'],
    imageSelectors: ['.v_news_content img', '.TRS_Editor img', '.content img', 'article img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '北京航空航天大学-新闻网',
    hostPatterns: [/^news\.buaa\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/info/"]',
      'ul.list a[href]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/info\/\d+\/\d+\.htm/i, /\/content\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/info\/1002\/$/i],
    contentSelectors: ['#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['h1', '.bt', '.article-title', 'title'],
    imageSelectors: ['.v_news_content img', '.TRS_Editor img', '.content img', 'article img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '西安交通大学-新闻网',
    hostPatterns: [/^news\.xjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/info/"]',
      'ul.list a[href]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.text a[href]',
      'a[href*="/kj/"]',
    ],
    articlePathPatterns: [/\/info\/\d+\/\d+\.htm/i, /\/info\/\d+\/\d+\.html/i, /\/kj\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/info\/\d+\/$/i],
    contentSelectors: ['#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['h1', '.bt', '.article-title', 'title'],
    imageSelectors: ['.v_news_content img', '.TRS_Editor img', '.content img', 'article img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '东南大学-新闻网',
    hostPatterns: [/^news\.seu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/"]',
      'ul.news-list a[href]',
      '.list a[href]',
      'h3 a[href], h4 a[href]',
      'a[href*="/c/"]',
    ],
    articlePathPatterns: [/\/\d{4}\/\d{4}\/c\//i, /\/content\//i, /\/article\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/list\.htm$/i, /\/rss\//i],
    contentSelectors: ['#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['h1', '.bt', '.article-title', 'title'],
    imageSelectors: ['.v_news_content img', '.TRS_Editor img', '.content img', 'article img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '北京理工大学-新闻网',
    hostPatterns: [/^www\.bit\.edu\.cn$/i, /^bit\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/xww/"]',
      'a[href*="/xsjl"]',
      'ul.list a[href]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/xww\/xzw\/xsjl/i, /\/xww\//i, /\/info\/\d+\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/xww\/$/i],
    contentSelectors: ['#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['h1', '.bt', '.article-title', 'title'],
    imageSelectors: ['.v_news_content img', '.TRS_Editor img', '.content img', 'article img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },

  {
    name: 'Nature',
    hostPatterns: [/^www\.nature\.com$/i, /^nature\.com$/i],
    articleLinkSelectors: [
      'article a[href]',
      'h2 a[href], h3 a[href]',
      'a[href*="/articles/"]',
      'a[href*="/news/"]',
    ],
    articlePathPatterns: [/\/articles\//i, /\/news\//i, /\/nature\//i],
    excludeUrlPatterns: [],
    contentSelectors: ['article', '.c-article-body', '.article-item__body', 'main'],
    titleSelectors: ['h1', '.c-article-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.c-article-section img', 'main img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },

  // ===== SJTU College Sources =====
  // Many SJTU sub-sites share one of two CMS platforms:
  //   CMS-A (smse, sese): /post/detail/NNNN URLs, content in .article-wrapper/.article-container
  //   CMS-B (scce): /index_news/NNNN.html URLs, content in .ab_nr, title in .sbt
  // Selectors include patterns for both + generic Chinese university CMS fallbacks.

  {
    name: '上海交大-机械与动力工程学院',
    hostPatterns: [/^me\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      '.list-right a[href]',
      'h3 a[href], h4 a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/index_xsrl\/\d+\.html$/i, /\/index_hyzh\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [
      /\/index\.htm$/i, /\/index\.html$/i, /\/rss\//i,
      /\/img\/ny\d+\.jpg$/i,
    ],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-电子信息与电气工程学院',
    hostPatterns: [/^www\.seiee\.sjtu\.edu\.cn$/i, /^seiee\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-材料科学与工程学院',
    hostPatterns: [/^smse\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      '.list-right a[href]',
      'h3 a[href], h4 a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-船舶海洋与建筑工程学院',
    hostPatterns: [/^oce\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/jianshe\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-航空航天学院',
    hostPatterns: [/^www\.aero\.sjtu\.edu\.cn$/i, /^aero\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-生物医学工程学院',
    hostPatterns: [/^bme\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/Web/Show/"]',
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      '.news-list a[href]',
      '.znCon a[href]',
      '.list1 a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/Web\/Show\/\d+$/i, /\/post\/detail\/\d+$/i, /\/info\/\d+\//i],
    excludeUrlPatterns: [
      /\/index\.htm$/i, /\/index\.html$/i,
      /\/Web\/(Notice|News|Content|List|Teacher|Faculty|Picture|Agency|Leader|Down|ResearchBase|Search|Login)\//i,
    ],
    contentSelectors: ['.article-wrapper', '.article-container', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-环境科学与工程学院',
    hostPatterns: [/^sese\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/research\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-化学化工学院',
    hostPatterns: [/^scce\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/index_news/"]',
      'a[href*="/index_xsrl/"]',
      'a[href*="/index_hyzh/"]',
      'a[href*="/index_notice/"]',
      'a[href*="/index_ssfc/"]',
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/index_news\/\d+\.html$/i, /\/index_xsrl\/\d+\.html$/i, /\/index_hyzh\/\d+\.html$/i, /\/index_notice\/\d+\.html$/i, /\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    excludeTitlePatterns: [/捐赠/, /签约/, /仪式/, /典礼/, /奖学金/, /颁奖/],
    contentSelectors: ['.ab_nr', '.ny_k3', '.article-wrapper', '.article-container', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.sbt', '.article-title', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-计算机学院',
    hostPatterns: [/^cs\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-物理与天文学院',
    hostPatterns: [/^www\.physics\.sjtu\.edu\.cn$/i, /^physics\.sjtu\.edu\.cn$/i, /^phys\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-数学科学学院',
    hostPatterns: [/^math\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-生命科学技术学院',
    hostPatterns: [/^life\.sjtu\.edu\.cn$/i, /^biosci\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-设计学院',
    hostPatterns: [/^design\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-媒体与传播学院',
    hostPatterns: [/^smc\.sjtu\.edu\.cn$/i, /^comm\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-海洋学院',
    hostPatterns: [/^soo\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-药学院',
    hostPatterns: [/^pharm\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-农业与生物学院',
    hostPatterns: [/^www\.agri\.sjtu\.edu\.cn$/i, /^agri\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-李政道研究所',
    hostPatterns: [/^tdli\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-医疗机器人研究院',
    hostPatterns: [/^imr\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/kxyj\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-金属基复合材料国家重点实验室',
    hostPatterns: [/^sklcm\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-密西根学院（全球学院）',
    hostPatterns: [/^www\.ji\.sjtu\.edu\.cn$/i, /^ji\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/news/"]',
      'a[href*="/info/"]',
      'a[href*="/post/detail/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
    ],
    articlePathPatterns: [/\/news\//i, /\/info\/\d+\//i, /\/post\/detail\/\d+$/i, /\/xwzx\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },
  {
    name: '上海交大-巴黎卓越工程师学院',
    hostPatterns: [/^speit\.sjtu\.edu\.cn$/i],
    articleLinkSelectors: [
      'a[href*="/post/detail/"]',
      'a[href*="/info/"]',
      'a[href*="/news/"]',
      '.news-list a[href]',
      'h3 a[href], h4 a[href]',
      '.list a[href]',
      '.text a[href]',
    ],
    articlePathPatterns: [/\/post\/detail\/\d+$/i, /\/info\/\d+\//i, /\/index_news\/\d+\.html$/i, /\/xwzx\//i, /\/tzgg\//i, /\/kyjz\//i, /\/news\//i],
    excludeUrlPatterns: [/\/index\.htm$/i, /\/index\.html$/i],
    contentSelectors: ['.article-wrapper', '.article-container', '.ab_nr', '.ny_k3', '#vsb_content', '.v_news_content', '.TRS_Editor', '.content', 'article', 'main'],
    titleSelectors: ['.article-title', '.sbt', 'h1', '.bt', '.news-title', 'title'],
    imageSelectors: ['.ab_nr img', '.article-wrapper img', '.article-container img', '.v_news_content img', '.TRS_Editor img', '.content img', 'article figure img', 'article img', 'main img', 'body img'],
    excludeSelectors: COMMON_EXCLUDE_SELECTORS,
  },

  // ===== Enterprise benchmark sources =====
  {
    name: 'Kongsberg Maritime',
    hostPatterns: [/^www\.kongsberg\.com$/i, /^kongsberg\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news/"]', 'a[href*="/newsroom/"]'],
    articlePathPatterns: [/\/news\//i, /\/newsroom\//i, /\/stories\//i, /\/maritime\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/contact/i, /\/careers/i],
    contentSelectors: ['article', 'main', '.article', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Arup Projects',
    hostPatterns: [/^www\.arup\.com$/i, /^arup\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.listing-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/projects/"]'],
    articlePathPatterns: [/\/projects\//i, /\/insights\//i],
    excludeUrlPatterns: [/\/projects\/all-projects\/?$/i, /\.pdf$/i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Autodesk Construction Blog',
    hostPatterns: [/^www\.autodesk\.com$/i, /^autodesk\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.post-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/customer-stories/"]', 'a[href*="/blogs/construction/"]'],
    articlePathPatterns: [/\/customer-stories\//i, /\/blogs\/construction\//i, /\/construction-cloud\/blog\//i],
    excludeUrlPatterns: [/\/tag\//i, /\/category\//i, /\/author\//i, /\.pdf$/i],
    contentSelectors: ['article', 'main', '.entry-content', '.post-content', '.content'],
    titleSelectors: ['h1', '.entry-title', '.post-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.entry-content img', '.post-content img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Siemens Energy',
    hostPatterns: [/^www\.siemens-energy\.com$/i, /^siemens-energy\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/press"]', 'a[href*="/stories/"]'],
    articlePathPatterns: [/\/press/i, /\/press-releases\//i, /\/stories\//i, /\/news\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investor/i],
    contentSelectors: ['article', 'main', '.press-release', '.content', '.rich-text'],
    titleSelectors: ['h1', '.headline', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Rolls-Royce',
    hostPatterns: [/^www\.rolls-royce\.com$/i, /^rolls-royce\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.listing a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/media/press-releases/"]'],
    articlePathPatterns: [/\/media\/press-releases\//i, /\/innovation\//i, /\/products-and-services\//i],
    excludeUrlPatterns: [
      /\.pdf$/i,
      /\/investors\//i,
      /\/support\//i,
      /\/resources\/press-releases\/?\?/i,
      /\/about-xylem\/newsroom\/?$/i,
    ],
    contentSelectors: ['article', 'main', '.article-content', '.body-content', '.content'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Caterpillar News',
    hostPatterns: [/^www\.cat\.com$/i, /^cat\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.news-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/articles/customer-stories"]', 'a[href*="/news/"]', 'a[href*="/machine-press-releases/"]'],
    articlePathPatterns: [/\/articles\/customer-stories/i, /\/customer-stories\//i, /\/news\//i, /\/machine-press-releases\//i, /\/press-releases\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/careers\//i, /\/dealers\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Huawei News',
    hostPatterns: [/^www\.huawei\.com$/i, /^huawei\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.news-list a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news/"]'],
    articlePathPatterns: [/\/news\//i, /\/media-center\//i, /\/technology-insights\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/events\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.detail-content'],
    titleSelectors: ['h1', '.title', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Qualcomm OnQ',
    hostPatterns: [/^www\.qualcomm\.com$/i, /^qualcomm\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.cmp-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news/onq/"]', 'a[href*="/news/releases/"]'],
    articlePathPatterns: [/\/news\/onq\//i, /\/news\/releases\//i, /\/news\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/support\//i],
    contentSelectors: ['article', 'main', '.article-body', '.cmp-text', '.content'],
    titleSelectors: ['h1', '.cmp-title__text', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'NVIDIA Technical Blog',
    hostPatterns: [/^developer\.nvidia\.com$/i, /^www\.nvidia\.com$/i, /^nvidia\.com$/i],
    articleLinkSelectors: ['article a[href]', '.post a[href]', '.card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/case-studies/"]', 'a[href*="/blog/"]'],
    articlePathPatterns: [/\/case-studies\//i, /\/customer-stories\//i, /\/solutions\//i, /\/blog\//i],
    excludeUrlPatterns: [/\/tag\//i, /\/category\//i, /\.pdf$/i],
    contentSelectors: ['article', 'main', '.entry-content', '.post-content', '.content'],
    titleSelectors: ['h1', '.entry-title', '.post-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.entry-content img', '.post-content img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'ABB News',
    hostPatterns: [/^new\.abb\.com$/i, /^www\.abb\.com$/i, /^abb\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news/"]'],
    articlePathPatterns: [/\/news\//i, /\/news\/detail\//i, /\/global\/en\/news\//i, /\/areas\/robotics\/news/i, /\/areas\/electrification\/news/i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investors\//i, /\/news-releases\/?$/i, /\/press-releases\/?$/i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Eaton News Releases',
    hostPatterns: [/^www\.eaton\.com$/i, /^eaton\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.news-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news-releases/"]', 'a[href*="/news-insights/"]'],
    articlePathPatterns: [/\/news-insights\/news-releases\//i, /\/news-releases\//i, /\/news\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investors\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.article-content img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Schneider Electric Newsroom',
    hostPatterns: [/^www\.se\.com$/i, /^se\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/newsroom/news/"]', 'a[href*="/press-releases/"]'],
    articlePathPatterns: [/\/newsroom\/news\//i, /\/press-releases\//i, /\/about-us\/newsroom\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/shop\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Boston Dynamics Blog',
    hostPatterns: [/^bostondynamics\.com$/i, /^www\.bostondynamics\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.post a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/blog/"]'],
    articlePathPatterns: [/\/blog\//i, /\/news\//i],
    excludeUrlPatterns: [/\/careers\//i, /\/support\//i],
    contentSelectors: ['article', 'main', '.post-content', '.entry-content', '.content'],
    titleSelectors: ['h1', '.entry-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.entry-content img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'FANUC America News',
    hostPatterns: [/^www\.fanucamerica\.com$/i, /^fanucamerica\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.news-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news"]'],
    articlePathPatterns: [/\/news-resources\/news/i, /\/news\//i, /\/resources\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/careers\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Google Research Blog',
    hostPatterns: [/^research\.google$/i, /^blog\.research\.google$/i],
    articleLinkSelectors: ['article a[href]', '.post a[href]', '.glue-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/blog/"]'],
    articlePathPatterns: [/\/blog\//i, /\/pubs\//i],
    excludeUrlPatterns: [/\/people\//i, /\/teams\//i, /\/label\//i],
    contentSelectors: ['article', 'main', '.post-body', '.blog-post', '.content'],
    titleSelectors: ['h1', '.post-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.post-body img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Microsoft Research Blog',
    hostPatterns: [/^www\.microsoft\.com$/i, /^microsoft\.com$/i, /^aiotlabs\.microsoft\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.post a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/customers/story/"]', 'a[href*="/case-study/"]', 'a[href*="/case-studies"]', 'a[href*="/ai/ai-customer-stories"]', 'a[href*="/research/blog/"]'],
    articlePathPatterns: [/\/customers\/story\//i, /\/case-study\//i, /\/case-studies/i, /\/ai\/ai-customer-stories/i, /\/research\/blog\//i, /\/research\/project\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/people\//i, /\/research\/blog\/?$/i],
    contentSelectors: ['article', 'main', '.entry-content', '.article-content', '.content'],
    titleSelectors: ['h1', '.entry-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.entry-content img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'ASML News',
    hostPatterns: [/^www\.asml\.com$/i, /^asml\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/en/news/"]'],
    articlePathPatterns: [/\/en\/news\//i, /\/en\/technology\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investors\//i, /\/support\//i, /\/resources\/press-releases\/?\?/i, /\/about-xylem\/newsroom\/?$/i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'TSMC Newsroom',
    hostPatterns: [/^pr\.tsmc\.com$/i, /^www\.tsmc\.com$/i, /^tsmc\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.news-list a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news"]'],
    articlePathPatterns: [/\/english\/news\//i, /\/news\//i, /\/english\/dedicatedFoundry\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investor/i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.news-content'],
    titleSelectors: ['h1', '.title', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Arm Newsroom',
    hostPatterns: [/^newsroom\.arm\.com$/i, /^www\.arm\.com$/i, /^arm\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.post a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/company/success-library/"]', 'a[href*="/news/"]', 'a[href*="/blog/"]'],
    articlePathPatterns: [/\/company\/success-library\//i, /\/success-library\//i, /\/news\//i, /\/blog\//i, /\/newsroom\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/company\//i],
    contentSelectors: ['article', 'main', '.entry-content', '.article-content', '.content'],
    titleSelectors: ['h1', '.entry-title', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.entry-content img', '.article-content img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'BASF News',
    hostPatterns: [/^www\.basf\.com$/i, /^basf\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/media/news-releases/"]'],
    articlePathPatterns: [/\/media\/news-releases\//i, /\/news-releases\//i, /\/stories\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investors\//i, /\/news-releases\/?$/i, /\/press-releases\/?$/i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Dow Press Releases',
    hostPatterns: [/^corporate\.dow\.com$/i, /^www\.dow\.com$/i, /^dow\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news/press-releases/"]'],
    articlePathPatterns: [/\/news\/press-releases\//i],
    excludeUrlPatterns: [
      /\.pdf$/i,
      /\/investors\//i,
      /\/news\/press-releases\.html$/i,
      /\/news\/seek-together\.html$/i,
      /\/news\/media-gallery\.html$/i,
      /\/news\/press-contacts\.html$/i,
      /\/purpose-in-action\/inclusion-and-diversity\//i,
      /\/purpose-in-action\/communities\//i,
      /\/purpose-in-action\/global-citizenship\//i,
      /financial/i,
      /earnings/i,
      /dividend/i,
    ],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.article-content img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Corning News',
    hostPatterns: [/^www\.corning\.com$/i, /^corning\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news-events/"]'],
    articlePathPatterns: [/\/news-events\//i, /\/news-releases\//i, /\/worldwide\/en\/innovation\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investor-relations\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Xylem Newsroom',
    hostPatterns: [/^www\.xylem\.com$/i, /^xylem\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.news-card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/about-xylem/newsroom/press-releases/"]'],
    articlePathPatterns: [/\/about-xylem\/newsroom\/press-releases\//i],
    excludeUrlPatterns: [
      /\.pdf$/i,
      /\/investors\//i,
      /\/support\//i,
      /\/resources\//i,
      /\/support\//i,
      /\/about-xylem\/newsroom\/?$/i,
      /\/about-xylem\/newsroom\/press-releases\/?$/i,
    ],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Veolia Newsroom',
    hostPatterns: [/^www\.veolia\.com$/i, /^veolia\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/en/newsroom/news/"]'],
    articlePathPatterns: [/\/en\/newsroom\/news\//i],
    excludeUrlPatterns: [
      /\.pdf$/i,
      /\/newsroom\/news\/?$/i,
      /\/investors\//i,
      /\/finance/i,
      /\/results/i,
      /annual-integrated-report/i,
      /double-a-rating-cdp/i,
      /ecological-transformation-awards/i,
      /young-leaders/i,
      /pickleball/i,
      /sustainable-sports/i,
    ],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.article-content img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Orsted News',
    hostPatterns: [/^orsted\.com$/i, /^www\.orsted\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/media-centre/news/"]'],
    articlePathPatterns: [/\/media-centre\/news\//i, /\/news\//i, /\/renewable-energy-solutions\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investors\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Siemens Healthineers',
    hostPatterns: [/^www\.siemens-healthineers\.com$/i, /^siemens-healthineers\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/press-room/"]', 'a[href*="/stories/"]'],
    articlePathPatterns: [/\/press-room\//i, /\/press-releases\//i, /\/stories\//i, /\/insights\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investor/i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'GE HealthCare Press Releases',
    hostPatterns: [/^www\.gehealthcare\.com$/i, /^gehealthcare\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/about/newsroom/press-releases/"]'],
    articlePathPatterns: [/\/about\/newsroom\/press-releases\//i],
    excludeUrlPatterns: [
      /\.pdf$/i,
      /\/investors\//i,
      /\/about\/newsroom\/?$/i,
      /\/about\/newsroom\/press-releases\/?$/i,
      /financial/i,
      /earnings/i,
      /quarter/i,
    ],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.article-content img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Boston Scientific Newsroom',
    hostPatterns: [/^news\.bostonscientific\.com$/i, /^www\.bostonscientific\.com$/i, /^bostonscientific\.com$/i],
    articleLinkSelectors: ['article a[href]', '.wd_item a[href]', '.card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/news-releases"]', 'a[href*="/press-releases"]'],
    articlePathPatterns: [/news-releases/i, /press-releases/i, /\/news\//i],
    excludeUrlPatterns: [
      /\.pdf$/i,
      /\/investors\//i,
      /\/news-releases\/?$/i,
      /\/press-releases\/?$/i,
      /share-repurchase/i,
      /strategic-investment/i,
      /accelerated-share/i,
      /\/Company-news\/?$/i,
      /quarter/i,
      /financial/i,
      /investment/i,
    ],
    contentSelectors: ['article', 'main', '.wd_body', '.article-content', '.content'],
    titleSelectors: ['h1', '.wd_title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.wd_body img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Airbus Newsroom',
    hostPatterns: [/^www\.airbus\.com$/i, /^airbus\.com$/i],
    articleLinkSelectors: ['article a[href]', '.card a[href]', '.teaser a[href]', 'h2 a[href], h3 a[href]', 'a[href*="/en/newsroom/"]'],
    articlePathPatterns: [/\/en\/newsroom\//i, /\/newsroom\//i, /\/innovation\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investors\//i],
    contentSelectors: ['article', 'main', '.article-content', '.content', '.rich-text'],
    titleSelectors: ['h1', '.page-title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', 'main figure img', 'main picture img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
  {
    name: 'Boeing Newsroom',
    hostPatterns: [/^boeing\.mediaroom\.com$/i, /^www\.boeing\.com$/i, /^boeing\.com$/i],
    articleLinkSelectors: ['article a[href]', '.wd_item a[href]', '.card a[href]', 'h2 a[href], h3 a[href]', 'a[href*="news-releases"]', 'a[href*="/news/"]'],
    articlePathPatterns: [/news-releases/i, /\/news\//i, /\/innovation\//i],
    excludeUrlPatterns: [/\.pdf$/i, /\/investors\//i],
    contentSelectors: ['article', 'main', '.wd_body', '.article-content', '.content'],
    titleSelectors: ['h1', '.wd_title', 'title'],
    imageSelectors: ['article figure img', 'article picture img', '.wd_body img', 'main img'],
    excludeSelectors: ENTERPRISE_EXCLUDE_SELECTORS,
  },
];

export function getStaticSourceAdapter(url: string): StaticSourceAdapter | null {
  let hostname = '';
  try {
    hostname = new URL(url).hostname;
  } catch {
    return null;
  }
  return STATIC_SOURCE_ADAPTERS.find(adapter =>
    adapter.hostPatterns.some(pattern => pattern.test(hostname))
  ) || null;
}
