export const theme = {
  colors: {
    bg: '#f6f6f7',
    bgCard: '#ffffff',
    bgSubtle: '#f1f1f3',
    border: '#e6e6eb',
    borderLight: '#f0f0f2',
    borderFocus: '#c4c4d4',
    text: {
      primary: '#1a1a1e',
      secondary: '#6f6f7b',
      tertiary: '#a0a0ad',
      disabled: '#c4c4ce',
    },
    accent: '#5b5bd7',
    accentBg: '#f0f0fb',
    accentBorder: '#d8d8f0',
    green: '#4a8c5c',
    greenBg: '#eef6ee',
    greenBorder: '#d0e4d0',
    red: '#b85c5c',
    redBg: '#fceeef',
    redBorder: '#e8d0d0',
    orange: '#b8864e',
    orangeBg: '#fef6ee',
    orangeBorder: '#eee0cc',
    yellow: '#a08c4e',
    yellowBg: '#fcf8e8',
    yellowBorder: '#e8e0c8',
    purple: '#8c6b8c',
    purpleBg: '#f5eef5',
    purpleBorder: '#e0d0e0',
    rating: '#e8a040',
    ratingBg: '#fef8ec',
    star: '#e8a040',
    starInactive: '#e0e0e6',
    white: '#ffffff',
  },
  typography: {
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontMono: '"SF Mono", "Fira Code", "Fira Mono", "Consolas", monospace',
    size: {
      xs: 11,
      sm: 12,
      base: 13,
      lg: 14,
      xl: 16,
      '2xl': 18,
      '3xl': 20,
      '4xl': 24,
      '5xl': 28,
      '6xl': 32,
    },
    weight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    '3xl': 32,
  },
  radius: {
    sm: 4,
    md: 6,
    lg: 8,
    xl: 12,
  },
  shadow: {
    card: '0 1px 2px rgba(0,0,0,0.04), 0 1px 4px rgba(0,0,0,0.02)',
    elevated: '0 2px 8px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
    popover: '0 4px 16px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)',
  },
  statusStyles: {
    pending_ai_analysis: {
      bg: '#f0f0f2',
      text: '#6f6f7b',
      border: '#e0e0e4',
    },
    needs_review: {
      bg: '#fef6ee',
      text: '#b8864e',
      border: '#eee0cc',
    },
    low_confidence_review: {
      bg: '#fcf8e8',
      text: '#a08c4e',
      border: '#e8e0c8',
    },
    approved: {
      bg: '#eef6ee',
      text: '#4a8c5c',
      border: '#d0e4d0',
    },
    rejected: {
      bg: '#fceeef',
      text: '#b85c5c',
      border: '#e8d0d0',
    },
    analysis_failed: {
      bg: '#f5eef5',
      text: '#8c6b8c',
      border: '#e0d0e0',
    },
    source_missing: {
      bg: '#f0f0f2',
      text: '#6f6f7b',
      border: '#e0e0e4',
    },
  } as Record<string, { bg: string; text: string; border: string }>,
};

export function statusStyle(status: string) {
  return theme.statusStyles[status] || theme.statusStyles.pending_ai_analysis;
}
